# **Loading the Data**

In [ ]:
from google.colab import drive
import pandas as pd
drive.mount('/content/gdrive')

nhanes = pd.read_csv("/content/gdrive/MyDrive/nhanescopy.csv")
nhanes

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDRETH1,DMQMILIZ,DMDBORN4,DMDYRUSR,DMDEDUC2,...,HIQ032F,HIQ032H,HIQ032I,HIQ210,INDFMMPC,INQ300,IND310,BPXOSY1,BPXODI1,LBXTC
0,132141.0,12.0,2.0,2.0,56.0,4.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,115.0,70.0,205.0
1,136977.0,12.0,2.0,1.0,29.0,3.0,2.0,2.0,2.0,5.0,...,NaN,NaN,NaN,2.0,3.0,2.0,2.0,125.0,71.0,193.0
2,134280.0,12.0,2.0,2.0,25.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,111.0,69.0,87.0
3,132522.0,12.0,2.0,2.0,64.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,113.0,90.0,215.0
4,138725.0,12.0,2.0,2.0,28.0,3.0,2.0,1.0,NaN,5.0,...,NaN,NaN,NaN,2.0,3.0,1.0,NaN,114.0,69.0,215.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5698,138255.0,12.0,2.0,2.0,65.0,5.0,2.0,1.0,NaN,4.0,...,NaN,8.0,NaN,2.0,1.0,2.0,1.0,99.0,62.0,144.0
5699,134584.0,12.0,2.0,1.0,56.0,1.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,2.0,3.0,2.0,3.0,137.0,102.0,235.0
5700,133659.0,12.0,2.0,2.0,80.0,3.0,2.0,1.0,NaN,4.0,...,NaN,NaN,9.0,2.0,NaN,NaN,NaN,126.0,65.0,156.0
5701,131701.0,12.0,2.0,2.0,46.0,3.0,2.0,1.0,NaN,3.0,...,NaN,NaN,NaN,1.0,2.0,1.0,NaN,121.0,76.0,291.0
5702,136760.0,12.0,2.0,2.0,73.0,5.0,2.0,1.0,NaN,4.0,...,NaN,NaN,NaN,2.0,3.0,2.0,4.0,122.0,71.0,271.0

In [ ]:
bp_purple = nhanes.copy().dropna(subset=['BPXOSY1', 'BPXODI1', 'HIQ032I'])
chol_purple = nhanes.copy().dropna(subset=['LBXTC', 'HIQ032I'])

# **Data Splitting**

In [ ]:
def create_bp_col(row):
  if pd.isna(row["BPXOSY1"]) or pd.isna(row["BPXODI1"]):
        return None
  if row["BPXOSY1"] < 120 and row["BPXODI1"] < 80:
    return "normal"
  else:
    return "abnormal"

nhanes["BP"] = nhanes.apply(create_bp_col, axis=1)


def create_chol_col(val):
  if pd.isna(val):
        return None
  if val < 200:
    return "normal"
  if val <= 239:
    return "borderline"
  return "high"

nhanes["CHOL"] = nhanes["LBXTC"].apply(create_chol_col)

nhanes = nhanes.drop(columns=["BPXOSY1","BPXODI1","LBXTC"])
nhanes[["BP","CHOL"]].head()

         BP        CHOL
0    normal  borderline
1  abnormal      normal
2    normal      normal
3  abnormal  borderline
4    normal  borderline

In [ ]:
from sklearn.model_selection import train_test_split

bp_purple = nhanes.copy().dropna(subset=['BP'])
chol_purple = nhanes.copy().dropna(subset=['CHOL'])

bp_training_purple, bp_test_purple = train_test_split(bp_purple, test_size=0.2, random_state=42)
chol_training_purple, chol_test_purple = train_test_split(chol_purple, test_size=0.2, random_state=42)

# **Pre processing**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, VotingClassifier, StackingClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import GradientBoostingClassifier, HistGradientBoostingClassifier

In [ ]:
from joblib.pool import TemporaryResourcesManager
from sklearn.pipeline import Pipeline,  make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, FunctionTransformer
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.decomposition import PCA, FastICA, TruncatedSVD
from sklearn.manifold import TSNE
from sklearn.model_selection import GridSearchCV, cross_validate, RandomizedSearchCV

binary_features = ['RIAGENDR','DMQMILIZ','DMDBORN4','ALQ111','ALQ151','HIQ011','INQ300'] #gender, active military, country of birth, ever had alc, daily 4-5+ drinks, covered by health insurance, savings>5000
# binary_features = ['RIAGENDR', 'DMQMILIZ', 'DMDBORN4', 'ALQ111', 'ALQ151', 'HIQ011', 'INQ300', 'is_elderly', 'heavy_drinker', 'binge_drinker', 'large_household', 'living_alone', 'immigrant', 'recent_immigrant', 'low_ses', 'ALQ121_missing', 'ALQ130_missing', 'ALQ170_missing', 'IND310_missing']
onehot_features = ['RIDRETH1','DMDMARTZ'] #hispanic/other race origin, marital status
ordinal_features = ['DMDYRUSR','DMDEDUC2','ALQ121','INDFMMPC','IND310'] #years in us, education age 20+, drinking frequency per 12 months, monthly poverty category, total savings category
numeric_features = ['RIDAGEYR','DMDHHSIZ','WTINT2YR','WTMEC2YR','ALQ130','ALQ170'] #age, household size, survey weight, survey weight, av drinks per day, 4/5+ drinks last 30 days
# numeric_features = ['RIDAGEYR', 'DMDHHSIZ', 'WTINT2YR', 'WTMEC2YR', 'ALQ130', 'ALQ170', 'RIDAGEYR_sq', 'alcohol_load', 'edu_income_score', 'insurance_count', 'age_gender']
insurance_features = ['HIQ032A','HIQ032B','HIQ032D','HIQ032F','HIQ032H','HIQ032I'] #private insurance, medicare, medicaid, military healthcare, state sponsored insurance, other insurance
id_features = ['SEQN'] #id
survey_features = ['SDDSRVYR', 'RIDSTATR'] #data release cycle, interview exam status


binary_transformer = Pipeline([("imputer", SimpleImputer(strategy="most_frequent")) #imputes binary features with most_frequent value
])
onehot_transformer = Pipeline([  #imputes categorical features with more frequent value, then one hot encodes
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])
ordinal_transformer = Pipeline([ #imputes ordinal features with median value, then scales
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())   # EDIT: scaling added
])
numeric_transformer = Pipeline([ #imputes numeric features with median value, then scales
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())   # EDIT: scaling added
])
insurance_transformer = Pipeline([ #imputes insurance features with most frequent value, then one hot encodes
    ("imputer", SimpleImputer(strategy="most_frequent")),
     ("encoder", OneHotEncoder(handle_unknown="ignore"))
     ])
survey_transformer = Pipeline([ #imputes survey features with most frequent value
    ("imputer", SimpleImputer(strategy="most_frequent"))
])
id_transformer = Pipeline([ #imputes id feature with most frequent value
    ("imputer", SimpleImputer(strategy="most_frequent"))
])
chol_transformer =Pipeline([  #imputes categorical features with more frequent value, then one hot encodes
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ])
bp_transformer =Pipeline([  #imputes categorical features with more frequent value, then one hot encodes
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
    ])


def clean_data(X):

    X = pd.DataFrame(X).copy()

    replace_vals = [7, 9, 77, 99, 777, 999]
    X = X.replace(replace_vals, np.nan)

    if 'ALQ121' in X.columns:
        X.loc[X['ALQ121'] < 1, 'ALQ121'] = np.nan

    if 'ALQ170' in X.columns:
        X.loc[X['ALQ170'] < 0.1, 'ALQ170'] = 0

    binary_map = {1.0: 1.0, 2.0: 0.0}
    binary_cols = ['RIAGENDR', 'DMQMILIZ', 'DMDBORN4', 'ALQ111', 'ALQ151', 'HIQ011', 'INQ300']
    for col in binary_cols:
        if col in X.columns:
            X[col] = X[col].replace(binary_map)
    return X

    # # FEATURE ENGINEERING

    # # age features
    # X["RIDAGEYR_sq"] = X["RIDAGEYR"] ** 2
    # X["is_elderly"] = (X["RIDAGEYR"] >= 65).astype(float)

    # # alcohol features
    # X["alcohol_load"] = (X["ALQ121"] * X["ALQ130"])
    # X["heavy_drinker"] = (X["ALQ130"] >= 5).astype(float)
    # X["binge_drinker"] = (X["ALQ170"] >= 8).astype(float)

    # # household features
    # X["large_household"] = (X["DMDHHSIZ"] >= 5).astype(float)
    # X["living_alone"] = (X["DMDHHSIZ"] == 1).astype(float)

    # # immigrant features
    # X["immigrant"] = (X["DMDBORN4"] == 0).astype(float)
    # X["recent_immigrant"] = ((X["DMDBORN4"] == 0) &(X["DMDYRUSR"] <= 2)).astype(float)

    # # socioeconomic features
    # X["low_ses"] = ((X["INDFMMPC"] == 1) & (X["DMDEDUC2"] <= 2)).astype(float)
    # X["edu_income_score"] = (X["DMDEDUC2"] * X["INDFMMPC"])

    # # insurance features
    # insurance_cols = ['HIQ032A', 'HIQ032B', 'HIQ032D', 'HIQ032F', 'HIQ032H', 'HIQ032I']
    # X["insurance_count"] = (X[insurance_cols].notna().sum(axis=1))

    # # interaction features
    # X["age_gender"] = (X["RIDAGEYR"] * X["RIAGENDR"])
    # X["age_alcohol"] = (X["RIDAGEYR"] * X["alcohol_load"])
    # X["poverty_insurance"] = (X["INDFMMPC"] * X["insurance_count"])
    # X["poverty_gender"] = (X["INDFMMPC"] * X["RIAGENDR"])
    # X["poverty_age"] = (X["INDFMMPC"] * X["RIDAGEYR"])
    # X["edu_alcohol"] = (X["DMDEDUC2"] * X["ALQ130"])


    # # missing indicators
    # missing_cols = ['ALQ121', 'ALQ130', 'ALQ170', 'IND310']

    # for col in missing_cols:
    #     X[col + "_missing"] = ( X[col].isna()).astype(float)


preprocessor_bp = ColumnTransformer([
    ("binary", binary_transformer, binary_features),
    ("onehot", onehot_transformer, onehot_features),
    ("ordinal", ordinal_transformer, ordinal_features),
    ("numeric", numeric_transformer, numeric_features),
    ("insurance", insurance_transformer, insurance_features),
    ("survey", survey_transformer, survey_features),
    ("id", id_transformer, id_features),
     ("chol", chol_transformer, ["CHOL"])
], remainder="drop")

preprocessor_chol = ColumnTransformer([
    ("binary", binary_transformer, binary_features),
    ("onehot", onehot_transformer, onehot_features),
    ("ordinal", ordinal_transformer, ordinal_features),
    ("numeric", numeric_transformer, numeric_features),
    ("insurance", insurance_transformer, insurance_features),
    ("survey", survey_transformer, survey_features),
    ("id", id_transformer, id_features),
    ("bp", bp_transformer, ["BP"])
], remainder="drop")

plineb = Pipeline([
    ("clean", FunctionTransformer(clean_data)),   # EDIT
    ("prep", preprocessor_bp),
    ('ICA', FastICA(n_components=20, random_state=42))
])

plinec = Pipeline([
    ("clean", FunctionTransformer(clean_data)),   # EDIT
    ("prep", preprocessor_chol),
    ('ICA', FastICA(n_components=20, random_state=42))
    ])

X_train_bp = bp_training_purple.drop(columns=["BP"])
X_train_chol = chol_training_purple.drop(columns=["CHOL"])

y_train_bp = bp_training_purple["BP"]
y_train_chol = chol_training_purple["CHOL"]

# **Grid search + Random search**

In [ ]:


param_grid = {
    "stump": [DecisionTreeClassifier(max_depth=1, random_state=42, class_weight="balanced"),
              {
                  'model__criterion': ['gini', 'entropy'],
              }],

    "tree": [DecisionTreeClassifier(max_depth=5, random_state=42, class_weight="balanced"),
             {
                 'model__max_depth': [3, 5, 7, 9, 11, None],
                 'model__criterion': ['gini', 'entropy'],
                 'model__min_samples_split': [2, 5, 10],
                 'model__min_samples_leaf': [1, 2, 4],
                 'model__max_features': ['sqrt', 'log2', None],
             }],

    "rf": [RandomForestClassifier(random_state=42, class_weight="balanced"),
           {
               'model__n_estimators': [100, 200, 500],
               'model__max_depth': [3, 5, 7, 9, 11, None],
               'model__criterion': ['gini', 'entropy'],
               'model__min_samples_split': [2, 5, 10],
               'model__min_samples_leaf': [1, 2, 4],
               'model__max_features': ['sqrt', 'log2', None]
           }],
    "ada": [AdaBoostClassifier(random_state=42),
            {
                'model__n_estimators': [50, 100, 200],
                'model__learning_rate': [0.01, 0.1, 1.0]
            }],
    "svm": [SVC(random_state=42, class_weight="balanced"),
            {
                'model__C': [0.1, 1, 10],
                'model__kernel': ['rbf', 'linear'],
                'model__gamma': ['scale', 'auto', 0.01]
            }],
    "nb": [GaussianNB(),
           {
               'model__var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6]
           }],

    "logreg": [LogisticRegression(random_state=42, class_weight="balanced"),
    [
        {'model__penalty': ['l2'], 'model__solver': ['lbfgs', 'newton-cg', 'sag'], 'model__C': [0.01, 0.1, 1, 10, 100], 'model__max_iter': [100, 500, 1000]},
        {'model__penalty': ['l1'], 'model__solver': ['liblinear', 'saga'], 'model__C': [0.01, 0.1, 1, 10, 100],'model__max_iter': [100, 500, 1000]},
        {'model__penalty': ['elasticnet'], 'model__solver': ['saga'], 'model__C': [0.01, 0.1, 1, 10, 100], 'model__l1_ratio': [0.5],'model__max_iter': [100, 500, 1000]},

    ]
    ],
    "knn": [KNeighborsClassifier(),
            {
                'model__n_neighbors': [3, 5, 7, 9, 11, 15],
                'model__weights': ['uniform', 'distance'],
                'model__algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                'model__metric': ['euclidean', 'manhattan', 'chebyshev', 'minkowski']
            }],
    "mlp": [MLPClassifier(random_state=42),
            {
              'model__hidden_layer_sizes': [(50,), (100,), (100, 100)],
              'model__activation': ['relu', 'tanh'],
              'model__solver': ['adam'],
              'model__alpha': [0.0001, 0.001],
              'model__learning_rate': ['constant', 'adaptive'],
              'model__max_iter': [500, 1000, 1500]
            }],

    "gb": [GradientBoostingClassifier(random_state=42),
           {
                'model__n_estimators': [50, 100, 200],
                'model__learning_rate': [0.01, 0.1, 1.0],
                'model__max_depth': [3, 5, 7, 9, 11]
           }],
    "hgb": [HistGradientBoostingClassifier(random_state=42),
            {
                'model__max_iter': [100, 200, 500],
                'model__learning_rate': [0.01, 0.1, 1.0],
                'model__max_depth': [3, 5, 7, 9, 11],
                'model__l2_regularization': [0.0, 0.1, 0.5]
            }]
}


grid_models = ['logreg', 'nb', 'ada', 'stump', 'tree', 'knn', 'gb']
random_models = ['rf', 'svm', 'mlp', 'hgb']

In [ ]:
for name in param_grid:

    print(f"\n--- {name} ---")

    if name in grid_models:
        search = GridSearchCV(estimator=Pipeline([
    ('prep', plinec),
    ('model', param_grid[name][0])
]), param_grid=param_grid[name][1], cv=10, n_jobs=-1)
    else:
        search = RandomizedSearchCV(estimator=Pipeline([
    ('prep', plinec),
    ('model', param_grid[name][0])
]), param_distributions=param_grid[name][1], n_iter=40, cv=10, random_state=42, n_jobs=-1)

    search.fit(X_train_chol, y_train_chol)
    print(search.best_params_)
    print(search.best_score_)

--- stump ---

ValueError: Invalid parameter 'model' for estimator DecisionTreeClassifier(class_weight='balanced', max_depth=1, random_state=42). Valid parameters are: ['ccp_alpha', 'class_weight', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'min_impurity_decrease', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'monotonic_cst', 'random_state', 'splitter'].

In [ ]:
for name in param_grid:
    print(f"\n--- {name} ---")
    if name in grid_models:
        search = GridSearchCV(estimator=
    Pipeline([
    ('prep', plinec),
    ('model', param_grid[name][0])
]), param_grid=param_grid[name][1], cv=10, scoring = 'f1_macro', n_jobs=-1)
    else:
        search = RandomizedSearchCV(estimator=
    Pipeline([
    ('prep', plinec),
    ('model', param_grid[name][0])
]), param_distributions=param_grid[name][1], n_iter=40, cv=10, scoring = 'f1_macro', random_state=42, n_jobs=-1)
    search.fit(X_train_chol, y_train_chol)
    print(search.best_params_)
    print(search.best_score_)



# --- stump ---
# /usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
#   warnings.warn(
# {'model__criterion': 'gini'}
# 0.306121482305952

# --- tree ---
# /usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
#   warnings.warn(
# {'model__criterion': 'entropy', 'model__max_depth': None, 'model__max_features': 'sqrt', 'model__min_samples_leaf': 2, 'model__min_samples_split': 2}
# 0.3683738591603889

# --- rf ---
# /usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
#   warnings.warn(
# {'model__n_estimators': 200, 'model__min_samples_split': 10, 'model__min_samples_leaf': 1, 'model__max_features': 'log2', 'model__max_depth': 9, 'model__criterion': 'gini'}
# 0.39654220259913836

# --- ada ---
# /usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
#   warnings.warn(
# {'model__learning_rate': 1.0, 'model__n_estimators': 200}
# 0.2636823322925438

# --- svm ---
# /usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 18 is smaller than n_iter=40. Running 18 iterations. For exhaustive searches, use GridSearchCV.
#   warnings.warn(
# /usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
#   warnings.warn(
# {'model__kernel': 'rbf', 'model__gamma': 'scale', 'model__C': 1}
# 0.37911361645361763

# --- nb ---
# /usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
#   warnings.warn(
# {'model__var_smoothing': 1e-09}
# 0.3025784504556678

# --- logreg ---
# /usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
#   warnings.warn(
# {'model__C': 0.01, 'model__max_iter': 100, 'model__penalty': 'l2', 'model__solver': 'lbfgs'}
# 0.3592460418800676

# --- knn ---
# /usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
#  0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
#         nan 0.3589767         nan 0.3527199         nan 0.33213761
#         nan 0.3297817         nan 0.33301869        nan 0.31265432
#         nan 0.3410497         nan 0.33964807        nan 0.3330969
#         nan 0.32890811        nan 0.31379706        nan 0.3008004
#  0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
#  0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
#  0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
#  0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
#  0.36381091 0.3589767  0.36244901 0.3527199  0.34104668 0.33213761
#  0.33609743 0.3297817  0.33587528 0.33301869 0.31869608 0.31265432
#  0.34204457 0.3410497  0.34165691 0.33964807 0.33308746 0.3330969
#  0.32629241 0.32890811 0.31695386 0.31379706 0.30436762 0.3008004
#  0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
#  0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
#  0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
#  0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
#  0.36381091 0.3589767  0.36244901 0.3527199  0.34104668 0.33213761
#  0.33609743 0.3297817  0.33587528 0.33301869 0.31869608 0.31265432
#  0.34204457 0.3410497  0.34165691 0.33964807 0.33308746 0.3330969
#  0.32629241 0.32890811 0.31695386 0.31379706 0.30436762 0.3008004
#  0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
#  0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
#  0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
#  0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
#         nan 0.3589767         nan 0.3527199         nan 0.33213761
#         nan 0.3297817         nan 0.33301869        nan 0.31265432
#         nan 0.3410497         nan 0.33964807        nan 0.3330969
#         nan 0.32890811        nan 0.31379706        nan 0.3008004
#  0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
#  0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717]
#   warnings.warn(
# /usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
#   warnings.warn(
# {'model__algorithm': 'ball_tree', 'model__metric': 'manhattan', 'model__n_neighbors': 3, 'model__weights': 'uniform'}
# 0.36381091093023765

# --- mlp ---

--- stump ---

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

{'model__criterion': 'gini'}
0.306121482305952

--- tree ---

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

{'model__criterion': 'entropy', 'model__max_depth': None, 'model__max_features': 'sqrt', 'model__min_samples_leaf': 2, 'model__min_samples_split': 2}
0.3683738591603889

--- rf ---

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

{'model__n_estimators': 200, 'model__min_samples_split': 10, 'model__min_samples_leaf': 1, 'model__max_features': 'log2', 'model__max_depth': 9, 'model__criterion': 'gini'}
0.39654220259913836

--- ada ---

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

{'model__learning_rate': 1.0, 'model__n_estimators': 200}
0.2636823322925438

--- svm ---

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:317: UserWarning: The total space of parameters 18 is smaller than n_iter=40. Running 18 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

{'model__kernel': 'rbf', 'model__gamma': 'scale', 'model__C': 1}
0.37911361645361763

--- nb ---

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

{'model__var_smoothing': 1e-09}
0.3025784504556678

--- logreg ---

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

{'model__C': 0.01, 'model__max_iter': 100, 'model__penalty': 'l2', 'model__solver': 'lbfgs'}
0.3592460418800676

--- knn ---

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
 0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
        nan 0.3589767         nan 0.3527199         nan 0.33213761
        nan 0.3297817         nan 0.33301869        nan 0.31265432
        nan 0.3410497         nan 0.33964807        nan 0.3330969
        nan 0.32890811        nan 0.31379706        nan 0.3008004
 0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
 0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
 0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
 0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
 0.36381091 0.3589767  0.36244901 0.3527199  0.34104668 0.33213761
 0.33609743 0.3297817  0.33587528 0.33301869 0.31869608 0.31265432
 0.34204457 0.3410497  0.34165691 0.33964807 0.33308746 0.3330969
 0.32629241 0.32890811 0.31695386 0.31379706 0.30436762 0.3008004
 0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
 0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
 0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
 0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
 0.36381091 0.3589767  0.36244901 0.3527199  0.34104668 0.33213761
 0.33609743 0.3297817  0.33587528 0.33301869 0.31869608 0.31265432
 0.34204457 0.3410497  0.34165691 0.33964807 0.33308746 0.3330969
 0.32629241 0.32890811 0.31695386 0.31379706 0.30436762 0.3008004
 0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
 0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
 0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
 0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717
        nan 0.3589767         nan 0.3527199         nan 0.33213761
        nan 0.3297817         nan 0.33301869        nan 0.31265432
        nan 0.3410497         nan 0.33964807        nan 0.3330969
        nan 0.32890811        nan 0.31379706        nan 0.3008004
 0.35458062 0.35918676 0.3609774  0.34478768 0.34116435 0.3286861
 0.33924009 0.32913647 0.33043688 0.32740159 0.31880711 0.31382717]
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

{'model__algorithm': 'ball_tree', 'model__metric': 'manhattan', 'model__n_neighbors': 3, 'model__weights': 'uniform'}
0.36381091093023765

--- mlp ---

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

{'model__solver': 'adam', 'model__max_iter': 1000, 'model__learning_rate': 'adaptive', 'model__hidden_layer_sizes': (100, 100), 'model__alpha': 0.001, 'model__activation': 'relu'}
0.3803372779418871

--- gb ---

# **05/08 cross validation after accuracy chol param**

In [ ]:
#original params

models = {
    "stump": DecisionTreeClassifier(max_depth=1, random_state=42, class_weight="balanced"),
    "tree": DecisionTreeClassifier(max_depth=5, random_state=42, class_weight="balanced"),
    "rf": RandomForestClassifier(random_state=42, class_weight="balanced"),
    "ada": AdaBoostClassifier(random_state=42),
    "svm": SVC(random_state=42, class_weight="balanced"),
    "nb": GaussianNB(),
    "logreg": LogisticRegression(random_state=42, max_iter=1000, class_weight="balanced"),
    "knn": KNeighborsClassifier(),
    "mlp": MLPClassifier(random_state=42, max_iter=1000),
    "gb": GradientBoostingClassifier(random_state=42),
    "hgb": HistGradientBoostingClassifier(random_state=42),

    "voting_clf": VotingClassifier(estimators=[
    ('stump', DecisionTreeClassifier(max_depth=1, random_state=42, class_weight="balanced")),
    ('ada', AdaBoostClassifier(random_state=42)),
    ('tree', DecisionTreeClassifier(max_depth=5, random_state=42, class_weight="balanced")),
    ('rfc', RandomForestClassifier(random_state=42, class_weight="balanced")),
    ('nb', GaussianNB()),
    ('lr', LogisticRegression(random_state=42, max_iter=1000, class_weight="balanced")),
    ('knn', KNeighborsClassifier()),
    ('svm', SVC(random_state=42, class_weight="balanced")),
     ('mlp', MLPClassifier(random_state=42, max_iter=1000)),
     ('gb', GradientBoostingClassifier(random_state=42)),
     ('hgb', HistGradientBoostingClassifier(random_state=42)),
    ], voting='hard'),

    "voting_clf_soft": VotingClassifier(estimators=[
        ('ada', AdaBoostClassifier(random_state=42)),
        ('rfc', RandomForestClassifier(random_state=42, class_weight="balanced")),
        ('nb', GaussianNB()),
        ('lr', LogisticRegression(random_state=42, max_iter=1000, class_weight="balanced")),
        ('svm', SVC(random_state=42, class_weight="balanced", probability=True)),
        ('gb', GradientBoostingClassifier(random_state=42)),
        ('hgb', HistGradientBoostingClassifier(random_state=42)),
    ], voting='soft'),

    "stacking_clf": StackingClassifier(
        estimators=[
            ('ada', AdaBoostClassifier(random_state=42)),
            ('tree', DecisionTreeClassifier(max_depth=5, random_state=42, class_weight="balanced")),
            ('rfc', RandomForestClassifier(random_state=42, class_weight="balanced")),
            ('nb', GaussianNB()),
            ('lr', LogisticRegression(random_state=42, max_iter=1000, class_weight="balanced")),
            ('svm', SVC(random_state=42, class_weight="balanced", probability=True)),
            ('gb', GradientBoostingClassifier(random_state=42)),
            ('hgb', HistGradientBoostingClassifier(random_state=42)),
        ],
        final_estimator=LogisticRegression(
            random_state=42,
            max_iter=1000
        )
    )
}

--- BP: stump ---
Feature Importance for stump:
ratio [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
features [ 4 19 17 18 16 15 13 14 11 10  9 12  8  7  6  5  3  2  1  0]
{'fit_time': array([0.08116889, 0.05690718, 0.04131198, 0.03703475, 0.03621602,
       0.03638029, 0.03746724, 0.03611231, 0.04483271, 0.06544757]), 'score_time': array([0.02796412, 0.02876902, 0.02357507, 0.03881001, 0.02331734,
       0.02528477, 0.02395296, 0.02240849, 0.05500865, 0.02309847]), 'test_accuracy': array([0.62358277, 0.60770975, 0.64172336, 0.61904762, 0.6553288 ,
       0.64399093, 0.6462585 , 0.63038549, 0.60454545, 0.65      ]), 'test_precision_macro': array([0.61485619, 0.59710843, 0.63443834, 0.61210471, 0.65430588,
       0.63592923, 0.64076421, 0.62169056, 0.5987341 , 0.64343821]), 'test_recall_macro': array([0.61239791, 0.5928377 , 0.63334031, 0.61210471, 0.65707853,
       0.63225131, 0.62374869, 0.61839791, 0.59938182, 0.63161547]), 'test_f1_macro': array([0.61297792, 0.59294118, 0.63376713, 0.61210471, 0.65338794,
       0.63309398, 0.62233202, 0.6190721 , 0.59894393, 0.63173112])}

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

--- CHOL: stump ---
Feature Importance for stump:
ratio [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
features [ 9 19 17 18 16 15 13 14 12 11 10  8  7  6  5  4  3  2  1  0]
{'fit_time': array([0.07845736, 0.06312895, 0.04847741, 0.07376218, 0.0566113 ,
       0.05057049, 0.09505844, 0.08038521, 0.05293179, 0.05339646]), 'score_time': array([0.02577639, 0.03854799, 0.0245223 , 0.02313733, 0.05121779,
       0.0334239 , 0.05172086, 0.02273607, 0.02012944, 0.03642297]), 'test_accuracy': array([0.51941748, 0.47572816, 0.51699029, 0.53398058, 0.51213592,
       0.45873786, 0.50121655, 0.50851582, 0.51581509, 0.49635036]), 'test_precision_macro': array([0.28883053, 0.27497606, 0.29149476, 0.29694307, 0.28234994,
       0.26250881, 0.27853989, 0.29293598, 0.28996585, 0.28560027]), 'test_recall_macro': array([0.40246894, 0.37991255, 0.42457207, 0.42750493, 0.38703141,
       0.35635965, 0.38076574, 0.42042018, 0.41252509, 0.40829653]), 'test_f1_macro': array([0.31867549, 0.29653256, 0.32692693, 0.33360516, 0.31027191,
       0.28304739, 0.30460367, 0.3220202 , 0.32167429, 0.31357383])}

--- BP: tree ---
Feature Importance for tree:
ratio [0.01257958 0.         0.03088139 0.04405386 0.50348076 0.01097033
 0.03553888 0.03852015 0.01802699 0.         0.         0.00886387
 0.         0.04420436 0.         0.04922549 0.02535861 0.
 0.1607317  0.01756405]
features [ 4 18 15 13  3  7  6  2 16  8 19  0  5 11 17 12  9 10 14  1]
{'fit_time': array([0.16784739, 0.1424365 , 0.18445921, 0.1213131 , 0.1887188 ,
       0.12850833, 0.17746663, 0.16335416, 0.23807096, 0.25332546]), 'score_time': array([0.02474618, 0.06352878, 0.04968715, 0.02311516, 0.02674675,
       0.06024241, 0.02695823, 0.05835032, 0.02463818, 0.07661247]), 'test_accuracy': array([0.65079365, 0.62131519, 0.63718821, 0.64852608, 0.66893424,
       0.60770975, 0.66213152, 0.64172336, 0.65909091, 0.66136364]), 'test_precision_macro': array([0.6440169 , 0.61384451, 0.62857858, 0.64246633, 0.66252263,
       0.59968374, 0.65493814, 0.63353369, 0.65596692, 0.65533586]), 'test_recall_macro': array([0.6320733 , 0.59371728, 0.6237801 , 0.62760209, 0.66166492,
       0.59901571, 0.64948691, 0.6246911 , 0.63720852, 0.64470447]), 'test_f1_macro': array([0.63226121, 0.58765432, 0.62452107, 0.62697482, 0.66203704,
       0.5992699 , 0.65063457, 0.62504843, 0.63636364, 0.64552773])}

--- CHOL: tree ---
Feature Importance for tree:
ratio [0.05260814 0.02419623 0.05943387 0.05268912 0.         0.
 0.25477566 0.         0.04174258 0.2126812  0.02230968 0.04991568
 0.         0.02896173 0.01660758 0.         0.         0.04182722
 0.11702555 0.02522575]
features [ 6  9 18  2  3  0 11 17  8 13 19  1 10 14 16 12 15  4  7  5]
{'fit_time': array([0.17315269, 0.16548753, 0.13575625, 0.12690568, 0.32590318,
       0.12764287, 0.12381101, 0.1910212 , 0.22554302, 0.30139899]), 'score_time': array([0.03574586, 0.02770019, 0.02016425, 0.02293205, 0.01945233,
       0.01983404, 0.04006219, 0.08044767, 0.06266356, 0.09408712]), 'test_accuracy': array([0.36407767, 0.34708738, 0.33495146, 0.42475728, 0.34223301,
       0.33980583, 0.37226277, 0.35036496, 0.41119221, 0.36739659]), 'test_precision_macro': array([0.39265014, 0.38861648, 0.42711481, 0.34913567, 0.40163495,
       0.35273032, 0.39995487, 0.3828032 , 0.41263737, 0.39516846]), 'test_recall_macro': array([0.39575136, 0.39916011, 0.41221445, 0.3799683 , 0.38114683,
       0.34470104, 0.43162237, 0.37396743, 0.4149735 , 0.39211248]), 'test_f1_macro': array([0.33232056, 0.32450038, 0.31282514, 0.34317126, 0.31772899,
       0.30200053, 0.35048954, 0.3126624 , 0.36374027, 0.33456699])}

--- BP: rf ---
Feature Importance for rf:
ratio [0.04439729 0.04317636 0.04519536 0.05035938 0.09860522 0.04427627
 0.04960178 0.04880852 0.04721242 0.04543115 0.04539446 0.04517875
 0.04601251 0.05131702 0.04930849 0.0453798  0.04303937 0.04290371
 0.06016105 0.05424111]
features [ 4 18 19 13  3  6 14  7  8 12  9 10 15  2 11  0  5  1 16 17]
{'fit_time': array([6.74091172, 2.79943275, 2.5316422 , 2.81256342, 3.63883257,
       2.59469128, 2.59669375, 2.56430531, 2.70562625, 3.61715269]), 'score_time': array([0.02895403, 0.02866817, 0.02829885, 0.04693055, 0.04784727,
       0.03035069, 0.02939582, 0.02860713, 0.04870248, 0.05171943]), 'test_accuracy': array([0.62811791, 0.6553288 , 0.63718821, 0.65306122, 0.66666667,
       0.66213152, 0.63718821, 0.65079365, 0.65454545, 0.65909091]), 'test_precision_macro': array([0.62248811, 0.65631232, 0.63500183, 0.6510512 , 0.6608637 ,
       0.66060577, 0.62996454, 0.6486285 , 0.65747794, 0.66057143]), 'test_recall_macro': array([0.60033508, 0.62804188, 0.60833508, 0.62789529, 0.6497801 ,
       0.63836649, 0.61513089, 0.62527749, 0.626485  , 0.63294014]), 'test_f1_macro': array([0.59448731, 0.62415897, 0.60207534, 0.62531861, 0.65080126,
       0.63701699, 0.6135816 , 0.62236432, 0.62150538, 0.6296795 ])}

--- CHOL: rf ---
Feature Importance for rf:
ratio [0.04806561 0.04742182 0.05215746 0.05014334 0.04621671 0.04530189
 0.06411511 0.05163876 0.04618796 0.06194559 0.04853122 0.05492735
 0.04699607 0.04703417 0.04826335 0.04190457 0.04624102 0.04992751
 0.05533888 0.0476416 ]
features [ 6  9 18 11  2  7  3 17 10 14  0 19  1 13 12 16  4  8  5 15]
{'fit_time': array([2.46726799, 2.44277644, 2.43661451, 3.48847532, 2.75529122,
       2.42817307, 2.390064  , 2.44809747, 3.05861521, 3.11941576]), 'score_time': array([0.02753711, 0.02779007, 0.04604602, 0.04122186, 0.02837253,
       0.0275085 , 0.02765727, 0.02823043, 0.039922  , 0.02750683]), 'test_accuracy': array([0.63592233, 0.63106796, 0.65291262, 0.64805825, 0.63349515,
       0.63349515, 0.63017032, 0.6350365 , 0.63017032, 0.62530414]), 'test_precision_macro': array([0.3814262 , 0.40431918, 0.47211986, 0.36622443, 0.40848966,
       0.41726308, 0.36363636, 0.4024795 , 0.41221258, 0.29235989]), 'test_recall_macro': array([0.345838  , 0.34383428, 0.35350115, 0.34304195, 0.33502061,
       0.33920366, 0.33838776, 0.34257279, 0.33372964, 0.32959787]), 'test_f1_macro': array([0.29621888, 0.30098099, 0.30774094, 0.28716641, 0.28033093,
       0.28945265, 0.28919239, 0.29585967, 0.27808737, 0.27520263])}

--- BP: ada ---
Feature Importance for ada:
ratio [0.0218293  0.         0.03446847 0.04843725 0.23054573 0.02466752
 0.05057082 0.         0.2562641  0.03981686 0.         0.
 0.         0.13634292 0.         0.         0.04298183 0.
 0.07528901 0.03878618]
features [ 8  4 13 18  6  3 16  9 19  2  5  0 17 11 14 12 15 10  7  1]
{'fit_time': array([1.08178759, 1.0935781 , 1.0848403 , 1.08482194, 1.07911897,
       1.19364047, 1.59627771, 1.60726476, 1.37701964, 1.08015728]), 'score_time': array([0.02450109, 0.04564214, 0.02440786, 0.02755594, 0.02467513,
       0.04187036, 0.04339457, 0.03977013, 0.02585673, 0.02548432]), 'test_accuracy': array([0.66213152, 0.6462585 , 0.66439909, 0.64172336, 0.70294785,
       0.66893424, 0.66213152, 0.64172336, 0.65681818, 0.67045455]), 'test_precision_macro': array([0.65676976, 0.64004787, 0.66431913, 0.6334308 , 0.69922342,
       0.66273292, 0.65712342, 0.63364539, 0.65412152, 0.67078822]), 'test_recall_macro': array([0.6433089 , 0.62498429, 0.63974869, 0.62901571, 0.68857592,
       0.65363351, 0.6426911 , 0.6240733 , 0.63398095, 0.64724868]), 'test_f1_macro': array([0.64381698, 0.6241313 , 0.63804348, 0.62984488, 0.69062907,
       0.65487779, 0.64303525, 0.62428824, 0.63258512, 0.64629245])}

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

--- CHOL: ada ---
Feature Importance for ada:
ratio [0.         0.         0.03700192 0.02735788 0.         0.
 0.13767592 0.07577454 0.         0.51769221 0.         0.04823749
 0.         0.         0.         0.         0.         0.
 0.10205505 0.054205  ]
features [ 9  6 18  7 19 11  2  3 16 17 15 14  8 10 13 12  4  5  1  0]
{'fit_time': array([1.02248168, 1.02120209, 1.17714787, 1.0245707 , 1.01562262,
       1.01411057, 1.13552833, 1.49643683, 1.50688434, 1.39547086]), 'score_time': array([0.02558255, 0.02526546, 0.0249908 , 0.02509952, 0.02581978,
       0.02581072, 0.04018855, 0.04358888, 0.03992677, 0.02540541]), 'test_accuracy': array([0.64563107, 0.64563107, 0.6407767 , 0.64563107, 0.64563107,
       0.64563107, 0.64720195, 0.64476886, 0.64476886, 0.64476886]), 'test_precision_macro': array([0.21521036, 0.21521036, 0.21463415, 0.21521036, 0.21521036,
       0.21521036, 0.21573398, 0.21492295, 0.21492295, 0.21492295]), 'test_recall_macro': array([0.33333333, 0.33333333, 0.33082707, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]), 'test_f1_macro': array([0.26155359, 0.26155359, 0.26035503, 0.26155359, 0.26155359,
       0.26155359, 0.26193993, 0.26134122, 0.26134122, 0.26134122])}

--- BP: svm ---
{'fit_time': array([0.88405943, 0.87533116, 0.88598108, 0.88889194, 0.87331486,
       0.91763401, 0.88185573, 0.85226917, 0.9317205 , 2.08490777]), 'score_time': array([0.09501934, 0.09484267, 0.09525323, 0.09583187, 0.09621119,
       0.09565639, 0.09523892, 0.11165404, 0.19126081, 0.17692733]), 'test_accuracy': array([0.63492063, 0.64399093, 0.66439909, 0.66213152, 0.66666667,
       0.66893424, 0.63945578, 0.64172336, 0.63863636, 0.65909091]), 'test_precision_macro': array([0.62673559, 0.63579336, 0.65826007, 0.65531661, 0.66070532,
       0.66215628, 0.63199966, 0.63337539, 0.63035714, 0.6532304 ]), 'test_recall_macro': array([0.62425131, 0.63101571, 0.6477801 , 0.64701571, 0.66090052,
       0.65610471, 0.63072251, 0.62839791, 0.62279484, 0.6414769 ]), 'test_f1_macro': array([0.62492274, 0.63187669, 0.64877954, 0.64812008, 0.66079941,
       0.65737548, 0.63119527, 0.62921456, 0.62322072, 0.64205137])}

--- CHOL: svm ---
{'fit_time': array([1.65164256, 1.22341919, 1.05554104, 1.0620656 , 1.05688   ,
       1.05131197, 1.05243158, 1.05894637, 1.05599284, 1.13353872]), 'score_time': array([0.17494488, 0.0986805 , 0.09985662, 0.09845829, 0.09926391,
       0.09766817, 0.10167265, 0.09934425, 0.09959626, 0.17559075]), 'test_accuracy': array([0.47572816, 0.42718447, 0.4538835 , 0.46601942, 0.47815534,
       0.48786408, 0.40875912, 0.46958637, 0.46472019, 0.42092457]), 'test_precision_macro': array([0.42047347, 0.36346387, 0.38566548, 0.40572932, 0.42097618,
       0.4266841 , 0.35108962, 0.41746281, 0.38772693, 0.36621964]), 'test_recall_macro': array([0.45973708, 0.35725893, 0.38584049, 0.42814564, 0.43974782,
       0.4501283 , 0.34873277, 0.43749228, 0.40692784, 0.37050851]), 'test_f1_macro': array([0.41307799, 0.34087734, 0.36789398, 0.39788557, 0.40429708,
       0.41303403, 0.33181886, 0.4010314 , 0.38275041, 0.34836578])}

--- BP: nb ---
{'fit_time': array([0.01209497, 0.01102376, 0.01135182, 0.01101112, 0.01112962,
       0.01132274, 0.01625299, 0.01119375, 0.01109266, 0.01121736]), 'score_time': array([0.02021813, 0.02037811, 0.01910663, 0.01903749, 0.01912069,
       0.0189414 , 0.01913881, 0.01884747, 0.01885223, 0.0198915 ]), 'test_accuracy': array([0.58503401, 0.66213152, 0.64852608, 0.64399093, 0.66439909,
       0.6462585 , 0.65306122, 0.63945578, 0.59318182, 0.64545455]), 'test_precision_macro': array([0.57422834, 0.65839182, 0.64119417, 0.63595295, 0.65784161,
       0.6382646 , 0.64538126, 0.63151203, 0.58125   , 0.63839685]), 'test_recall_macro': array([0.5722199 , 0.6408377 , 0.6306911 , 0.6273089 , 0.64901571,
       0.63425131, 0.64086911, 0.6202199 , 0.57653651, 0.62698963]), 'test_f1_macro': array([0.57233248, 0.640575  , 0.63104202, 0.62779208, 0.65015009,
       0.63513514, 0.64185735, 0.61991208, 0.5758271 , 0.62694841])}

--- CHOL: nb ---
{'fit_time': array([0.0113492 , 0.01092052, 0.01073694, 0.01068997, 0.01070619,
       0.01076579, 0.01091671, 0.01079798, 0.011127  , 0.01072717]), 'score_time': array([0.017946  , 0.01701784, 0.01695418, 0.01696229, 0.01703739,
       0.01701307, 0.0214746 , 0.01748943, 0.01715064, 0.01674366]), 'test_accuracy': array([0.63106796, 0.62864078, 0.61650485, 0.6092233 , 0.62621359,
       0.62135922, 0.62287105, 0.60583942, 0.62773723, 0.63746959]), 'test_precision_macro': array([0.64760982, 0.39281052, 0.28974126, 0.28545078, 0.38478452,
       0.37203939, 0.36747619, 0.29768154, 0.33582888, 0.41293986]), 'test_recall_macro': array([0.3464507 , 0.34842021, 0.32886509, 0.32510569, 0.34817217,
       0.34646885, 0.34597512, 0.32164411, 0.33718315, 0.36231984]), 'test_f1_macro': array([0.30910339, 0.31291731, 0.28349524, 0.27924253, 0.31652841,
       0.31182272, 0.31559049, 0.27602638, 0.2929443 , 0.33712607])}

--- BP: logreg ---
{'fit_time': array([0.02907681, 0.03904939, 0.03675485, 0.04057479, 0.04326677,
       0.04351568, 0.04052067, 0.04262233, 0.04061174, 0.0447247 ]), 'score_time': array([0.04984117, 0.04941201, 0.04972577, 0.04410434, 0.04384828,
       0.04478431, 0.04505968, 0.0463655 , 0.04470086, 0.04454255]), 'test_accuracy': array([0.60090703, 0.65079365, 0.65306122, 0.66666667, 0.65759637,
       0.68027211, 0.67346939, 0.64852608, 0.63181818, 0.675     ]), 'test_precision_macro': array([0.59717577, 0.6460199 , 0.64714721, 0.66095204, 0.6574455 ,
       0.67406705, 0.66960521, 0.64392684, 0.62562145, 0.66864724]), 'test_recall_macro': array([0.59857592, 0.64751832, 0.64766492, 0.66151832, 0.66031414,
       0.67290052, 0.67184293, 0.64551832, 0.62591728, 0.66650897]), 'test_f1_macro': array([0.59707629, 0.64642857, 0.64737516, 0.66120359, 0.65600446,
       0.67339339, 0.67003367, 0.64431227, 0.62575605, 0.66728535])}

--- CHOL: logreg ---
{'fit_time': array([0.05436778, 0.034868  , 0.03094125, 0.04722452, 0.03156638,
       0.04083323, 0.05828094, 0.04703474, 0.04634333, 0.06999183]), 'score_time': array([0.02616644, 0.03366613, 0.02536774, 0.04478979, 0.02565646,
       0.03437805, 0.03378153, 0.01816821, 0.03992105, 0.05469394]), 'test_accuracy': array([0.43446602, 0.39805825, 0.4223301 , 0.4538835 , 0.45631068,
       0.42961165, 0.41119221, 0.40875912, 0.44282238, 0.44768856]), 'test_precision_macro': array([0.3943179 , 0.36642294, 0.36918285, 0.40867906, 0.41556076,
       0.39180404, 0.3714744 , 0.36454018, 0.38565716, 0.39537838]), 'test_recall_macro': array([0.43904006, 0.36668638, 0.37599506, 0.42671395, 0.41689518,
       0.40211392, 0.3684401 , 0.38980248, 0.39251176, 0.41836483]), 'test_f1_macro': array([0.37751114, 0.32972536, 0.34700546, 0.38717013, 0.37810805,
       0.35927635, 0.33902312, 0.34138196, 0.36204552, 0.37378571])}

--- BP: knn ---
{'fit_time': array([0.01950359, 0.00897145, 0.00889373, 0.00893807, 0.00890136,
       0.00896096, 0.01052547, 0.00909662, 0.0088346 , 0.00904608]), 'score_time': array([0.09142089, 0.04374456, 0.04146004, 0.04109597, 0.04114699,
       0.04187417, 0.04199457, 0.04147816, 0.04109001, 0.04210877]), 'test_accuracy': array([0.59637188, 0.63038549, 0.58730159, 0.61451247, 0.65986395,
       0.63945578, 0.57596372, 0.60090703, 0.57954545, 0.625     ]), 'test_precision_macro': array([0.58468685, 0.62125958, 0.57612086, 0.60403727, 0.65253411,
       0.63247414, 0.56590038, 0.5912622 , 0.56912879, 0.61614891]), 'test_recall_macro': array([0.58036649, 0.6159267 , 0.57360209, 0.5982199 , 0.64748691,
       0.63195812, 0.5648377 , 0.5893089 , 0.56753716, 0.61257596]), 'test_f1_macro': array([0.58002696, 0.61647059, 0.57361878, 0.59814537, 0.64858691,
       0.63218578, 0.56500388, 0.58966334, 0.56764451, 0.6131528 ])}

--- CHOL: knn ---
{'fit_time': array([0.00888824, 0.00997591, 0.01322508, 0.00865197, 0.00872016,
       0.00886059, 0.00862932, 0.00877905, 0.008847  , 0.008883  ]), 'score_time': array([0.04853535, 0.05316639, 0.0392189 , 0.03732729, 0.03681278,
       0.03653359, 0.03701949, 0.03695345, 0.03698802, 0.03697801]), 'test_accuracy': array([0.59951456, 0.57524272, 0.54368932, 0.55582524, 0.5776699 ,
       0.58980583, 0.54987835, 0.55474453, 0.57664234, 0.54501217]), 'test_precision_macro': array([0.43689614, 0.40573074, 0.33777778, 0.39335443, 0.3768797 ,
       0.40345697, 0.36564609, 0.35301075, 0.34357243, 0.35269884]), 'test_recall_macro': array([0.39639988, 0.38326231, 0.34311278, 0.35209855, 0.37283732,
       0.39096998, 0.35107145, 0.35231264, 0.3524578 , 0.34939033]), 'test_f1_macro': array([0.40187172, 0.38514835, 0.33763286, 0.35333817, 0.36980452,
       0.3919142 , 0.35047349, 0.34938389, 0.34247905, 0.34726373])}

--- BP: mlp ---

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

{'fit_time': array([14.66873121, 16.67982268, 15.42529225, 15.44029593,  9.12764692,
       11.894104  , 15.39641142, 15.52690291, 15.75051785, 15.71625876]), 'score_time': array([0.04146171, 0.01990581, 0.02079368, 0.02090001, 0.02302456,
       0.01943517, 0.01937795, 0.0206821 , 0.02019644, 0.0211823 ]), 'test_accuracy': array([0.55555556, 0.57142857, 0.57369615, 0.61678005, 0.6553288 ,
       0.61678005, 0.59410431, 0.59183673, 0.55227273, 0.60227273]), 'test_precision_macro': array([0.55110583, 0.56038808, 0.56255639, 0.60962466, 0.64859573,
       0.60997113, 0.59166186, 0.58858893, 0.54166667, 0.59468929]), 'test_recall_macro': array([0.5517801 , 0.55898429, 0.56098429, 0.60948691, 0.64781152,
       0.61010471, 0.59319372, 0.58995812, 0.5410017 , 0.59432494]), 'test_f1_macro': array([0.55087916, 0.55901167, 0.56099886, 0.60955255, 0.64814815,
       0.61003469, 0.59106803, 0.58827801, 0.54098465, 0.59447859])}

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

--- CHOL: mlp ---
{'fit_time': array([15.49428105, 15.0750494 , 15.87119555, 14.5836587 , 14.65326881,
       15.46476531, 15.00178003, 15.93775988, 15.73745227, 13.18813443]), 'score_time': array([0.02556086, 0.04115677, 0.01710081, 0.01675177, 0.01757646,
       0.01738667, 0.01697946, 0.01795697, 0.01980138, 0.01814246]), 'test_accuracy': array([0.5315534 , 0.55582524, 0.53398058, 0.55339806, 0.53883495,
       0.55339806, 0.55961071, 0.52311436, 0.54257908, 0.55717762]), 'test_precision_macro': array([0.37420635, 0.3686206 , 0.35253226, 0.39471687, 0.38491531,
       0.39757092, 0.35981716, 0.36953055, 0.36179784, 0.40087193]), 'test_recall_macro': array([0.37137896, 0.36478177, 0.3513897 , 0.38577612, 0.3830913 ,
       0.39633309, 0.35729521, 0.3661183 , 0.36078732, 0.39378098]), 'test_f1_macro': array([0.37225904, 0.36426976, 0.35088887, 0.38835021, 0.38382107,
       0.39601829, 0.3548295 , 0.36729172, 0.35956225, 0.39621314])}

--- BP: gb ---
{'fit_time': array([4.72221446, 5.529392  , 4.94183302, 4.70785642, 5.7240653 ,
       4.7294209 , 4.69075179, 5.80898261, 4.67949128, 4.6911025 ]), 'score_time': array([0.01463103, 0.02348208, 0.0172646 , 0.0147202 , 0.02398467,
       0.01419044, 0.01500463, 0.0144136 , 0.01402688, 0.01433039]), 'test_accuracy': array([0.68027211, 0.65759637, 0.68480726, 0.66666667, 0.69614512,
       0.68480726, 0.67120181, 0.63718821, 0.64545455, 0.67727273]), 'test_precision_macro': array([0.68377442, 0.65585466, 0.69745358, 0.66358519, 0.69437086,
       0.68435866, 0.66935216, 0.63025871, 0.64595932, 0.68292063]), 'test_recall_macro': array([0.65560209, 0.63313089, 0.65589529, 0.6454555 , 0.67825131,
       0.6639267 , 0.6494555 , 0.61451309, 0.61723333, 0.65144347]), 'test_f1_macro': array([0.65470538, 0.63119126, 0.65274607, 0.6453995 , 0.68001949,
       0.66469748, 0.64938782, 0.61264822, 0.61154499, 0.64942993])}

--- CHOL: gb ---
{'fit_time': array([14.22669601, 14.22436643, 14.25678062, 14.20637608, 14.25059175,
       14.24109697, 14.1938026 , 14.22831821, 14.28330588, 14.33666134]), 'score_time': array([0.01475406, 0.01436162, 0.01478195, 0.01433563, 0.01460457,
       0.0150013 , 0.02412772, 0.01655722, 0.01491261, 0.01482105]), 'test_accuracy': array([0.63349515, 0.64320388, 0.64563107, 0.6407767 , 0.64320388,
       0.63592233, 0.64233577, 0.6350365 , 0.64476886, 0.63990268]), 'test_precision_macro': array([0.38779757, 0.36674111, 0.45988432, 0.31695761, 0.38283828,
       0.32719151, 0.46798134, 0.36861111, 0.46746432, 0.3283208 ]), 'test_recall_macro': array([0.33713448, 0.34053568, 0.35507827, 0.33716868, 0.33842181,
       0.33691371, 0.35324634, 0.33624537, 0.34971338, 0.33714504]), 'test_f1_macro': array([0.28449069, 0.28673955, 0.31252497, 0.27921819, 0.27974414,
       0.28327857, 0.31509651, 0.27921299, 0.30447872, 0.2795627 ])}

--- BP: hgb ---
{'fit_time': array([0.42334199, 0.40821099, 0.38168597, 0.40974116, 0.39743018,
       0.40149045, 0.39697981, 0.39280963, 0.40706301, 0.4983561 ]), 'score_time': array([0.01984239, 0.01911497, 0.01907492, 0.01881218, 0.02168918,
       0.01875615, 0.01895666, 0.018929  , 0.01859474, 0.02983403]), 'test_accuracy': array([0.64399093, 0.63945578, 0.67800454, 0.6553288 , 0.68707483,
       0.64399093, 0.63038549, 0.6553288 , 0.6       , 0.64772727]), 'test_precision_macro': array([0.63678397, 0.63121634, 0.67897603, 0.64856756, 0.68229814,
       0.63656357, 0.62123852, 0.6490523 , 0.58809865, 0.64396156]), 'test_recall_macro': array([0.6242199 , 0.6214555 , 0.6548377 , 0.6379267 , 0.67210471,
       0.6248377 , 0.6122199 , 0.6366911 , 0.58134107, 0.62411951]), 'test_f1_macro': array([0.62386936, 0.62152052, 0.65451075, 0.63855578, 0.67378859,
       0.62469306, 0.61199903, 0.63703704, 0.58000694, 0.62189882])}

--- CHOL: hgb ---
{'fit_time': array([1.86771679, 1.8658185 , 1.36111188, 1.10977554, 1.11163878,
       1.11977601, 1.15309191, 1.11047745, 1.1202445 , 1.12222767]), 'score_time': array([0.04487872, 0.03830147, 0.02810073, 0.02804708, 0.02769685,
       0.0299983 , 0.02857351, 0.02705812, 0.02770329, 0.02750564]), 'test_accuracy': array([0.62864078, 0.61650485, 0.61407767, 0.61407767, 0.60679612,
       0.60436893, 0.62773723, 0.60583942, 0.60097324, 0.63017032]), 'test_precision_macro': array([0.39187495, 0.41441618, 0.35097335, 0.30404178, 0.33819289,
       0.40242988, 0.43550336, 0.37464992, 0.33166215, 0.42415993]), 'test_recall_macro': array([0.3531505 , 0.35534032, 0.33979264, 0.33818131, 0.34237485,
       0.3470432 , 0.37459149, 0.35440421, 0.33339929, 0.37541939]), 'test_f1_macro': array([0.32504897, 0.33581108, 0.3077433 , 0.3038858 , 0.31754705,
       0.32672219, 0.36456939, 0.33819661, 0.30267126, 0.36226838])}

--- BP: voting_clf ---

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

{'fit_time': array([25.72866702, 26.57362223, 26.09188485, 25.55702615, 20.51862383,
       21.96744776, 26.46845889, 26.45372891, 26.73638844, 26.47299504]), 'score_time': array([0.17160106, 0.16813421, 0.33238554, 0.28487468, 0.1657145 ,
       0.17514181, 0.17119122, 0.17589855, 0.16922164, 0.28146505]), 'test_accuracy': array([0.64852608, 0.6553288 , 0.67120181, 0.66666667, 0.6893424 ,
       0.68480726, 0.65759637, 0.65986395, 0.65681818, 0.66590909]), 'test_precision_macro': array([0.64161512, 0.65126971, 0.669967  , 0.66060965, 0.68405257,
       0.68154708, 0.651172  , 0.65408769, 0.65469223, 0.66253754]), 'test_recall_macro': array([0.6294555 , 0.63298429, 0.6488377 , 0.65039791, 0.67595812,
       0.66701571, 0.6399267 , 0.6413089 , 0.63337118, 0.64567169]), 'test_f1_macro': array([0.62947404, 0.63201581, 0.64853218, 0.65149959, 0.67764706,
       0.66843361, 0.64056352, 0.64181287, 0.63165627, 0.64573463])}

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

--- CHOL: voting_clf ---
{'fit_time': array([35.55523181, 36.25021243, 36.09455705, 35.44431114, 35.24913669,
       35.39048767, 36.17309451, 35.98734426, 37.43044758, 32.93358254]), 'score_time': array([0.18452215, 0.35818362, 0.19072819, 0.28883219, 0.20055509,
       0.21841669, 0.18220377, 0.18090439, 0.18612218, 0.18380737]), 'test_accuracy': array([0.63349515, 0.6407767 , 0.63592233, 0.62378641, 0.6407767 ,
       0.61650485, 0.61800487, 0.62773723, 0.6350365 , 0.60827251]), 'test_precision_macro': array([0.44120724, 0.42586335, 0.4299885 , 0.32933455, 0.44298475,
       0.40530466, 0.38475177, 0.41818182, 0.40769147, 0.31384468]), 'test_recall_macro': array([0.37428274, 0.3673691 , 0.36647416, 0.33423582, 0.36847788,
       0.35395035, 0.34655408, 0.37008003, 0.35635061, 0.33246151]), 'test_f1_macro': array([0.34976378, 0.3440577 , 0.34179117, 0.28693415, 0.33691133,
       0.32689134, 0.31462538, 0.34613144, 0.32317188, 0.29267133])}

--- BP: voting_clf_soft ---
{'fit_time': array([14.78170586, 14.84751773, 14.65168881, 14.74731684, 14.71948075,
       14.73115921, 14.64045453, 14.53772926, 14.628546  , 14.67064643]), 'score_time': array([0.13892317, 0.13722539, 0.13958287, 0.13874936, 0.14035392,
       0.13844919, 0.13638091, 0.13862658, 0.14057541, 0.13675547]), 'test_accuracy': array([0.6462585 , 0.66213152, 0.67573696, 0.65306122, 0.69387755,
       0.67800454, 0.65759637, 0.66213152, 0.63409091, 0.67045455]), 'test_precision_macro': array([0.63878676, 0.6579335 , 0.67594021, 0.64618309, 0.68946635,
       0.67422928, 0.65057829, 0.65676976, 0.62751548, 0.66880952]), 'test_recall_macro': array([0.6280733 , 0.6414555 , 0.6528377 , 0.6353089 , 0.67934031,
       0.6597801 , 0.6417801 , 0.6433089 , 0.61085178, 0.64907799]), 'test_f1_macro': array([0.6282744 , 0.6414145 , 0.65251674, 0.63580277, 0.68118263,
       0.66091618, 0.64271573, 0.64381698, 0.60825301, 0.64890848])}

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
#accuracy based params
models = {
    "stump": DecisionTreeClassifier(criterion= 'gini', max_depth=1, random_state=42, class_weight="balanced"),
    "tree": DecisionTreeClassifier(criterion= 'gini', max_depth=None, max_features= 'sqrt', min_samples_leaf=1, min_samples_split=2, random_state=42, class_weight="balanced"),
    "rf": RandomForestClassifier(criterion='entropy', max_depth= None, max_features= 'log2', min_samples_leaf=1, min_samples_split=5, n_estimators=500, random_state=42, class_weight="balanced"),
    "ada": AdaBoostClassifier(n_estimators=200, learning_rate = 1.0, random_state=42),
    "svm": SVC(kernel='rbf', gamma='scale', C=10, random_state=42, class_weight="balanced"),
    "nb": GaussianNB(var_smoothing= 1e-09),
    "logreg": LogisticRegression(C= 0.01, max_iter= 100, penalty= 'elasticnet', solver='saga', l1_ratio=0.5,  random_state=42, class_weight="balanced"),
    "knn": KNeighborsClassifier(algorithm= 'auto', metric='chebyshev', n_neighbors= 15, weights= 'distance'),
    "mlp": MLPClassifier(solver='adam', max_iter= 500, learning_rate= 'constant', hidden_layer_sizes= (50,),alpha= 0.0001, activation='relu', random_state=42),
    "gb": GradientBoostingClassifier(learning_rate= 0.01, max_depth= 3, n_estimators= 200, random_state=42),
    "hgb": HistGradientBoostingClassifier(max_iter= 100, max_depth= 3, learning_rate= 0.01, l2_regularization= 0.1, random_state=42),

    "voting_clf": VotingClassifier(estimators=[
    ('stump', DecisionTreeClassifier(criterion= 'gini', max_depth=1, random_state=42, class_weight="balanced")),
    ('ada', AdaBoostClassifier(n_estimators=200, learning_rate = 1.0, random_state=42)),
    ('tree', DecisionTreeClassifier(criterion= 'gini', max_depth=None, max_features= 'sqrt', min_samples_leaf=1, min_samples_split=2, random_state=42, class_weight="balanced")),
    ('rfc',RandomForestClassifier(criterion='entropy', max_depth= None, max_features= 'log2', min_samples_leaf=1, min_samples_split=5, n_estimators=500, random_state=42, class_weight="balanced")),
    ('nb', GaussianNB(var_smoothing= 1e-09)),
    ('lr', LogisticRegression(C= 0.01, max_iter= 100, penalty= 'elasticnet', solver='saga', l1_ratio=0.5,  random_state=42, class_weight="balanced")),
    ('knn', KNeighborsClassifier(algorithm= 'auto', metric='chebyshev', n_neighbors= 15, weights= 'distance')),
    ('svm', SVC(kernel='rbf', gamma='scale', C=10, random_state=42, class_weight="balanced")),
     ('mlp', MLPClassifier(solver='adam', max_iter= 500, learning_rate= 'constant', hidden_layer_sizes= (50,),alpha= 0.0001, activation='relu', random_state=42)),
     ('gb', GradientBoostingClassifier(learning_rate= 0.01, max_depth= 3, n_estimators= 200, random_state=42)),
     ('hgb', HistGradientBoostingClassifier(max_iter= 100, max_depth= 3, learning_rate= 0.01, l2_regularization= 0.1, random_state=42)),
    ], voting='hard'),

    "voting_clf_soft": VotingClassifier(estimators=[
        ('ada', AdaBoostClassifier(n_estimators=200, learning_rate = 1.0, random_state=42)),
        ('rfc',RandomForestClassifier(criterion='entropy', max_depth= None, max_features= 'log2', min_samples_leaf=1, min_samples_split=5, n_estimators=500, random_state=42, class_weight="balanced")),
        ('nb', GaussianNB(var_smoothing= 1e-09)),
        ('lr', LogisticRegression(C= 0.01, max_iter= 100, penalty= 'elasticnet', solver='saga', l1_ratio=0.5,  random_state=42, class_weight="balanced")),
        ('svm', SVC(kernel='rbf', gamma='scale', C=10, random_state=42, probability=True, class_weight="balanced")),
        ('gb', GradientBoostingClassifier(learning_rate= 0.01, max_depth= 3, n_estimators= 200, random_state=42)),
        ('hgb', HistGradientBoostingClassifier(max_iter= 100, max_depth= 3, learning_rate= 0.01, l2_regularization= 0.1, random_state=42)),
    ], voting='soft'),

    "stacking_clf": StackingClassifier(
        estimators=[
            ('ada', AdaBoostClassifier(n_estimators=200, learning_rate = 1.0, random_state=42)),
            ('tree', DecisionTreeClassifier(criterion= 'gini', max_depth=None, max_features= 'sqrt', min_samples_leaf=1, min_samples_split=2, random_state=42, class_weight="balanced")),
            ('rfc', RandomForestClassifier(criterion='entropy', max_depth= None, max_features= 'log2', min_samples_leaf=1, min_samples_split=5, n_estimators=500, random_state=42, class_weight="balanced")),
            ('nb', GaussianNB(var_smoothing= 1e-09)),
            ('lr', LogisticRegression(C= 0.01, max_iter= 100, penalty= 'elasticnet', solver='saga', l1_ratio=0.5,  random_state=42, class_weight="balanced")),
            ('svm', SVC(kernel='rbf', gamma='scale', C=10, random_state=42, class_weight="balanced")),
            ('gb', GradientBoostingClassifier(learning_rate= 0.01, max_depth= 3, n_estimators= 200, random_state=42)),
            ('hgb', HistGradientBoostingClassifier(max_iter= 100, max_depth= 3, learning_rate= 0.01, l2_regularization= 0.1, random_state=42)),
        ],
        final_estimator=LogisticRegression(C= 0.01, max_iter= 100, penalty= 'elasticnet', solver='saga', l1_ratio=0.5,  random_state=42, class_weight="balanced")
    )
}

In [ ]:
scoring_list = ["accuracy", "precision_macro", "recall_macro", "f1_macro"]

In [ ]:
chol_results = {}
# Conduct 10-fold cross validation
for name in models:
    chol_cv = cross_validate(make_pipeline(plinec,models[name]), chol_training_purple.drop(columns=['CHOL']), chol_training_purple['CHOL'], cv=10, scoring=scoring_list)
    print(f"\n--- CHOL: {name} ---")
    chol_results[name] = chol_cv
    print(chol_results[name])

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: stump ---
{'fit_time': array([0.39904666, 0.2764802 , 0.22615838, 0.45919275, 0.27207541,
       0.24780178, 0.29611063, 0.3194859 , 0.22874069, 0.56028628]), 'score_time': array([0.05872154, 0.06555963, 0.05639553, 0.05586624, 0.05595541,
       0.05586338, 0.05586815, 0.05685592, 0.0555172 , 0.07578301]), 'test_accuracy': array([0.48786408, 0.4684466 , 0.48786408, 0.52427184, 0.51699029,
       0.45145631, 0.52554745, 0.49878345, 0.50121655, 0.45985401]), 'test_precision_macro': array([0.28314392, 0.27655502, 0.28559177, 0.29356337, 0.27431778,
       0.25916907, 0.27644757, 0.29037205, 0.28974009, 0.27518127]), 'test_recall_macro': array([0.39785634, 0.38199221, 0.41537354, 0.4224924 , 0.36618141,
       0.35260025, 0.37577988, 0.41538873, 0.41081226, 0.38942861]), 'test_f1_macro': array([0.30690728, 0.29509483, 0.31287243, 0.32833722, 0.30233766,
       0.27929057, 0.3088483 , 0.31687508, 0.31612055, 0.29453092])}

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: tree ---
{'fit_time': array([1.2207284 , 0.97181296, 0.91676545, 1.27616644, 0.46043611,
       0.383744  , 0.30027008, 0.32406402, 0.35443258, 0.4199543 ]), 'score_time': array([0.05989552, 0.05841708, 0.08408618, 0.0909133 , 0.07750463,
       0.05540609, 0.05523658, 0.05776906, 0.05563664, 0.05623269]), 'test_accuracy': array([0.51213592, 0.5461165 , 0.52912621, 0.48543689, 0.49029126,
       0.51941748, 0.50364964, 0.53041363, 0.45012165, 0.52068127]), 'test_precision_macro': array([0.34417901, 0.39910064, 0.37687842, 0.32547112, 0.33312867,
       0.36420343, 0.35803003, 0.3765282 , 0.30228145, 0.3581993 ]), 'test_recall_macro': array([0.3438367 , 0.39842514, 0.37485612, 0.32371063, 0.3335636 ,
       0.36032044, 0.35673149, 0.37523313, 0.30033373, 0.35790313]), 'test_f1_macro': array([0.34338726, 0.39854894, 0.37567312, 0.32405357, 0.33308122,
       0.36153333, 0.35708185, 0.37514143, 0.30108692, 0.35587715])}

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: rf ---
{'fit_time': array([18.79409051, 19.1640327 , 20.20258904, 19.83897138, 19.12730479,
       20.33756471, 18.60509562, 18.70820117, 20.24362612, 18.69907069]), 'score_time': array([0.13003635, 0.16237283, 0.12868977, 0.12684417, 0.16889572,
       0.12258077, 0.12741971, 0.12930107, 0.12160707, 0.12271309]), 'test_accuracy': array([0.65048544, 0.63349515, 0.6407767 , 0.64563107, 0.64805825,
       0.63349515, 0.63017032, 0.63990268, 0.62773723, 0.63990268]), 'test_precision_macro': array([0.50350315, 0.42683847, 0.40887636, 0.33954545, 0.42228821,
       0.33990103, 0.40757021, 0.41298186, 0.28661844, 0.33867644]), 'test_recall_macro': array([0.37087399, 0.34508741, 0.34300775, 0.34178882, 0.34676714,
       0.34210526, 0.34637506, 0.34719766, 0.33085573, 0.33925418]), 'test_f1_macro': array([0.33594314, 0.30208403, 0.29216373, 0.28650469, 0.29557138,
       0.29801612, 0.30707188, 0.30309299, 0.27527487, 0.2850682 ])}

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

--- CHOL: ada ---
{'fit_time': array([4.58350444, 5.90214777, 4.42631984, 4.62037206, 5.89156079,
       4.35222006, 4.46879148, 6.49561405, 4.39035535, 4.91985106]), 'score_time': array([0.09167314, 0.0917747 , 0.09085965, 0.09095311, 0.09556842,
       0.0908432 , 0.09568739, 0.0948174 , 0.09184527, 0.1549685 ]), 'test_accuracy': array([0.64563107, 0.64563107, 0.64563107, 0.64563107, 0.64563107,
       0.64563107, 0.64963504, 0.64720195, 0.64476886, 0.64476886]), 'test_precision_macro': array([0.28370188, 0.21521036, 0.21521036, 0.21521036, 0.21521036,
       0.21521036, 0.5495935 , 0.54878049, 0.21492295, 0.21492295]), 'test_recall_macro': array([0.3354472 , 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33673469, 0.33670034, 0.33333333, 0.33333333]), 'test_f1_macro': array([0.26891645, 0.26155359, 0.26155359, 0.26155359, 0.26155359,
       0.26155359, 0.26906142, 0.26839506, 0.26134122, 0.26134122])}

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: svm ---
{'fit_time': array([3.21616292, 1.8377862 , 1.58343458, 1.74738574, 1.63732243,
       1.58233929, 1.70499873, 3.85227275, 1.57633948, 1.64498401]), 'score_time': array([0.24219489, 0.1666646 , 0.16880488, 0.16693711, 0.16852045,
       0.18156958, 0.24474502, 0.23981071, 0.16395736, 0.17937517]), 'test_accuracy': array([0.50970874, 0.50485437, 0.44660194, 0.48300971, 0.52669903,
       0.49029126, 0.47201946, 0.486618  , 0.50121655, 0.4136253 ]), 'test_precision_macro': array([0.41293149, 0.39977286, 0.34718175, 0.3785148 , 0.41018876,
       0.38023143, 0.36621466, 0.39967295, 0.37809961, 0.33219298]), 'test_recall_macro': array([0.43379106, 0.4137676 , 0.34392773, 0.38547476, 0.41648663,
       0.39435643, 0.36594526, 0.40595004, 0.38235317, 0.32912667]), 'test_f1_macro': array([0.41331342, 0.39879545, 0.33807933, 0.37772003, 0.40786358,
       0.38176353, 0.36332171, 0.39112244, 0.3788401 , 0.32180462])}

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: nb ---
{'fit_time': array([0.37249303, 0.29303241, 0.24255347, 0.44967556, 0.23167658,
       0.32022858, 0.19625902, 0.26805377, 0.23675227, 0.37636018]), 'score_time': array([0.05510139, 0.05488276, 0.05454803, 0.05996799, 0.05463839,
       0.05836797, 0.06237507, 0.05480695, 0.05511808, 0.05592489]), 'test_accuracy': array([0.62864078, 0.63106796, 0.61893204, 0.6092233 , 0.62378641,
       0.62378641, 0.62530414, 0.60827251, 0.61800487, 0.6350365 ]), 'test_precision_macro': array([0.6367847 , 0.41653508, 0.29333808, 0.28545078, 0.368301  ,
       0.37783692, 0.36702822, 0.29799302, 0.29721285, 0.42371429]), 'test_recall_macro': array([0.34308369, 0.35551241, 0.33011822, 0.32510569, 0.34480517,
       0.34772198, 0.34508003, 0.32290198, 0.33004256, 0.36106198]), 'test_f1_macro': array([0.30355651, 0.32457378, 0.28435355, 0.27924253, 0.3113431 ,
       0.31298404, 0.31221042, 0.27666599, 0.28474372, 0.33611086])}

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: logreg ---
{'fit_time': array([0.42510033, 0.36015439, 0.33080578, 0.56125236, 0.35155821,
       0.34449625, 0.3167212 , 1.1255281 , 1.49087238, 1.5211184 ]), 'score_time': array([0.05849361, 0.04142833, 0.04067945, 0.04400444, 0.04262662,
       0.04396796, 0.06983113, 0.05989099, 0.06361175, 0.07083988]), 'test_accuracy': array([0.45873786, 0.41262136, 0.41262136, 0.42961165, 0.4538835 ,
       0.41504854, 0.43309002, 0.44038929, 0.43065693, 0.43552311]), 'test_precision_macro': array([0.39968581, 0.37606595, 0.3605724 , 0.36582318, 0.39310362,
       0.37150945, 0.38494475, 0.38151598, 0.38670282, 0.38791096]), 'test_recall_macro': array([0.43727684, 0.38165557, 0.37209131, 0.38136578, 0.4050727 ,
       0.37816267, 0.38709997, 0.39870429, 0.39205679, 0.39991376]), 'test_f1_macro': array([0.38216076, 0.33805482, 0.33527752, 0.34915345, 0.36420166,
       0.33689889, 0.3529528 , 0.36067121, 0.35767627, 0.35840211])}

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: knn ---
{'fit_time': array([0.74883938, 0.23922729, 0.20867109, 0.45866346, 0.21974897,
       0.25546432, 0.17406464, 0.2522285 , 0.23079133, 0.39613509]), 'score_time': array([0.1996491 , 0.12616134, 0.13181853, 0.12142229, 0.12487769,
       0.12316227, 0.12168837, 0.12354231, 0.12141156, 0.12067533]), 'test_accuracy': array([0.63106796, 0.61165049, 0.61893204, 0.62135922, 0.64320388,
       0.62621359, 0.6107056 , 0.62043796, 0.62287105, 0.6107056 ]), 'test_precision_macro': array([0.4544942 , 0.3992381 , 0.34006999, 0.28865671, 0.4974359 ,
       0.38008658, 0.33373819, 0.3608284 , 0.31007188, 0.27876225]), 'test_recall_macro': array([0.34594815, 0.34437857, 0.33595729, 0.33137136, 0.35644156,
       0.3432838 , 0.32896832, 0.34346219, 0.33888571, 0.32626898]), 'test_f1_macro': array([0.30726683, 0.31772509, 0.29602912, 0.28357559, 0.32151069,
       0.30490581, 0.28819586, 0.31025527, 0.29839545, 0.28014426])}

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: mlp ---
{'fit_time': array([6.34331346, 8.09045434, 6.08465743, 8.16022348, 6.23200727,
       7.99791431, 6.10318875, 7.92814207, 6.35579157, 7.54328156]), 'score_time': array([0.040694  , 0.04242897, 0.04286766, 0.04134607, 0.04072285,
       0.04065108, 0.04102707, 0.06741142, 0.04066133, 0.05779982]), 'test_accuracy': array([0.58495146, 0.59466019, 0.55825243, 0.58980583, 0.60194175,
       0.58495146, 0.59367397, 0.56447689, 0.56447689, 0.57177616]), 'test_precision_macro': array([0.39358638, 0.39457409, 0.34283833, 0.37325289, 0.41442374,
       0.41104449, 0.38333229, 0.34690432, 0.35985875, 0.37551502]), 'test_recall_macro': array([0.37136388, 0.37798774, 0.34278233, 0.36903617, 0.38647742,
       0.38405538, 0.37054262, 0.34679837, 0.35150974, 0.35366728]), 'test_f1_macro': array([0.37037991, 0.37572077, 0.33556318, 0.36122003, 0.38688809,
       0.38593644, 0.36581036, 0.33982303, 0.34632639, 0.34521326])}

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: gb ---
{'fit_time': array([28.72610927, 29.52209997, 28.53442597, 30.103616  , 28.99041462,
       28.70427585, 28.79539084, 28.66532826, 29.0378387 , 28.9141016 ]), 'score_time': array([0.08501625, 0.2055037 , 0.06864572, 0.0692215 , 0.06788087,
       0.04685998, 0.04689527, 0.04813099, 0.04749894, 0.04807949]), 'test_accuracy': array([0.64563107, 0.64320388, 0.64563107, 0.64563107, 0.64563107,
       0.64563107, 0.64963504, 0.64233577, 0.64476886, 0.64476886]), 'test_precision_macro': array([0.21521036, 0.21650327, 0.21521036, 0.21521036, 0.21521036,
       0.21521036, 0.5495935 , 0.21515892, 0.21492295, 0.21544715]), 'test_recall_macro': array([0.33333333, 0.3320802 , 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33673469, 0.33207547, 0.33333333, 0.33333333]), 'test_f1_macro': array([0.26155359, 0.26211672, 0.26155359, 0.26155359, 0.26155359,
       0.26155359, 0.26906142, 0.2611276 , 0.26134122, 0.2617284 ])}

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: hgb ---
{'fit_time': array([0.75780058, 0.64586496, 0.60203385, 0.85475063, 0.86734319,
       1.85741377, 1.45636845, 1.21406221, 0.693645  , 0.79482818]), 'score_time': array([0.05332899, 0.05580091, 0.05414343, 0.05811501, 0.07468104,
       0.07461286, 0.08073759, 0.05586696, 0.05583024, 0.05325723]), 'test_accuracy': array([0.64563107, 0.64563107, 0.64563107, 0.64563107, 0.64563107,
       0.64563107, 0.64720195, 0.64476886, 0.64476886, 0.64476886]), 'test_precision_macro': array([0.21521036, 0.21521036, 0.21521036, 0.21521036, 0.21521036,
       0.21521036, 0.21573398, 0.21492295, 0.21492295, 0.21492295]), 'test_recall_macro': array([0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]), 'test_f1_macro': array([0.26155359, 0.26155359, 0.26155359, 0.26155359, 0.26155359,
       0.26155359, 0.26193993, 0.26134122, 0.26134122, 0.26134122])}

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: voting_clf ---
{'fit_time': array([60.29609871, 60.64752388, 60.21778178, 60.54565382, 60.05497813,
       59.79897404, 59.78137279, 61.50180888, 61.25033355, 60.63058019]), 'score_time': array([0.38048744, 0.36855149, 0.38466167, 0.37714291, 0.36562419,
       0.36980605, 0.46632051, 0.55685663, 0.55197096, 0.3649354 ]), 'test_accuracy': array([0.65533981, 0.64563107, 0.64320388, 0.65048544, 0.65048544,
       0.63106796, 0.64963504, 0.63990268, 0.6350365 , 0.63017032]), 'test_precision_macro': array([0.45620223, 0.38448845, 0.32732733, 0.41756979, 0.58395062,
       0.37211083, 0.35090312, 0.26432707, 0.21375921, 0.21316872]), 'test_recall_macro': array([0.36754119, 0.34501146, 0.33419407, 0.34218121, 0.35547067,
       0.33934539, 0.3462646 , 0.33665195, 0.32830189, 0.32578616]), 'test_f1_macro': array([0.32501702, 0.28883036, 0.26805155, 0.28212759, 0.30735728,
       0.28757187, 0.28853785, 0.27382272, 0.25892857, 0.25771144])}

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: voting_clf_soft ---
{'fit_time': array([59.88277888, 60.1219883 , 59.60548115, 60.19642162, 59.85888815,
       59.22886467, 59.04944348, 59.61213589, 59.23854995, 59.31317782]), 'score_time': array([0.32844162, 0.32428741, 0.3368578 , 0.33006263, 0.33643508,
       0.31968856, 0.32544684, 0.32712507, 0.33944774, 0.33139968]), 'test_accuracy': array([0.64563107, 0.64320388, 0.64563107, 0.64563107, 0.64563107,
       0.64563107, 0.64720195, 0.64233577, 0.64476886, 0.64476886]), 'test_precision_macro': array([0.21521036, 0.21703522, 0.21521036, 0.21521036, 0.21573398,
       0.21521036, 0.21573398, 0.21463415, 0.21492295, 0.21492295]), 'test_recall_macro': array([0.33333333, 0.3320802 , 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33207547, 0.33333333, 0.33333333]), 'test_f1_macro': array([0.26155359, 0.26250619, 0.26155359, 0.26155359, 0.26193993,
       0.26155359, 0.26193993, 0.26074074, 0.26134122, 0.26134122])}

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: stacking_clf ---
{'fit_time': array([264.50445795, 264.29745722, 264.84223771, 265.7114563 ,
       266.22221899, 264.96157289, 264.90167332, 264.78778529,
       265.03111506, 265.68972707]), 'score_time': array([0.32507563, 0.32839775, 0.32783699, 0.32015371, 0.32545352,
       0.31970215, 0.32724237, 0.44861317, 0.45939803, 0.45545053]), 'test_accuracy': array([0.49029126, 0.50485437, 0.43932039, 0.47087379, 0.51213592,
       0.49271845, 0.44525547, 0.45498783, 0.46958637, 0.39902676]), 'test_precision_macro': array([0.47820985, 0.41151717, 0.34607555, 0.27856124, 0.41962351,
       0.48126984, 0.26456061, 0.34412159, 0.28005585, 0.32086086]), 'test_recall_macro': array([0.46645816, 0.43733124, 0.35617789, 0.37740628, 0.43102383,
       0.3981755 , 0.35194369, 0.38157164, 0.38862572, 0.36852778]), 'test_f1_macro': array([0.36299488, 0.36795641, 0.33395324, 0.29474307, 0.36079795,
       0.33841634, 0.27741324, 0.31032136, 0.29799182, 0.29297057])}

In [ ]:
for name in models:
    print(f"\n--- BP: {name} ---")
    print("Accuracy:", bp_results[name]["test_accuracy"].mean())
    print("Precision:", bp_results[name]["test_precision_macro"].mean())
    print("Recall:", bp_results[name]["test_recall_macro"].mean())
    print("F1_macro:", bp_results[name]["test_f1_macro"].mean())

In [ ]:
for name in models:
    print(f"\n--- CHOL: {name} ---")
    print("Accuracy:", chol_results[name]["test_accuracy"].mean())
    print("Precision:", chol_results[name]["test_precision_macro"].mean())
    print("Recall:", chol_results[name]["test_recall_macro"].mean())
    print("F1_macro:", chol_results[name]["test_f1_macro"].mean())
# 05.12.26
# --- CHOL: stump ---
# Accuracy: 0.4922294663737509
# Precision: 0.2804081907378314
# Recall: 0.39279056357272146
# F1_macro: 0.306121482305952

# --- CHOL: tree ---
# Accuracy: 0.5087390451893322
# Precision: 0.35380002660558807
# Recall: 0.35249141167843223
# F1_macro: 0.35254647796114724

# --- CHOL: rf ---
# Accuracy: 0.6389654642949945
# Precision: 0.38867996256532916
# Recall: 0.34533129888668473
# F1_macro: 0.298079102975937

# --- CHOL: ada ---
# Accuracy: 0.6460161103630737
# Precision: 0.2887973551675455
# Recall: 0.33422155677794774
# F1_macro: 0.2636823322925438

# --- CHOL: svm ---
# Accuracy: 0.4834644367278482
# Precision: 0.3805001289098701
# Recall: 0.3871179353060705
# F1_macro: 0.37726242172531543

# --- CHOL: nb ---
# Accuracy: 0.6222054898070063
# Precision: 0.37641949373833616
# Recall: 0.3405433716228027
# F1_macro: 0.3025784504556678

# --- CHOL: logreg ---
# Accuracy: 0.4322183639241254
# Precision: 0.38078349167080106
# Recall: 0.39333996762084494
# F1_macro: 0.35354494877360787

# --- CHOL: knn ---
# Accuracy: 0.6217147379113221
# Precision: 0.36433821903340347
# Recall: 0.33949659244951624
# F1_macro: 0.3008003970073593

# --- CHOL: mlp ---
# Accuracy: 0.5808966999740155
# Precision: 0.3795330304372709
# Recall: 0.3654220930103732
# F1_macro: 0.3612881466785069

# --- CHOL: gb ---
# Accuracy: 0.6452867739116057
# Precision: 0.2487677574670244
# Recall: 0.33342236994102514
# F1_macro: 0.2623143298346896

# --- CHOL: hgb ---
# Accuracy: 0.6455294923582077
# Precision: 0.21517649745273587
# Recall: 0.33333333333333337
# F1_macro: 0.26152851336307964

# --- CHOL: voting_clf ---
# Accuracy: 0.6430958117780454
# Precision: 0.35838073752949967
# Recall: 0.34207485889264355
# F1_macro: 0.2837956262664401

# --- CHOL: voting_clf_soft ---
# Accuracy: 0.6450434649091725
# Precision: 0.21538246559380392
# Recall: 0.33308223388660335
# F1_macro: 0.26160235957696115

# --- CHOL: stacking_clf ---
# Accuracy: 0.4679050622445846
# Precision: 0.36248560850675293
# Recall: 0.3957241728252065
# F1_macro: 0.3237558879988812

--- CHOL: stump ---
Accuracy: 0.4922294663737509
Precision: 0.2804081907378314
Recall: 0.39279056357272146
F1_macro: 0.306121482305952

--- CHOL: tree ---
Accuracy: 0.5087390451893322
Precision: 0.35380002660558807
Recall: 0.35249141167843223
F1_macro: 0.35254647796114724

--- CHOL: rf ---
Accuracy: 0.6389654642949945
Precision: 0.38867996256532916
Recall: 0.34533129888668473
F1_macro: 0.298079102975937

--- CHOL: ada ---
Accuracy: 0.6460161103630737
Precision: 0.2887973551675455
Recall: 0.33422155677794774
F1_macro: 0.2636823322925438

--- CHOL: svm ---
Accuracy: 0.4834644367278482
Precision: 0.3805001289098701
Recall: 0.3871179353060705
F1_macro: 0.37726242172531543

--- CHOL: nb ---
Accuracy: 0.6222054898070063
Precision: 0.37641949373833616
Recall: 0.3405433716228027
F1_macro: 0.3025784504556678

--- CHOL: logreg ---
Accuracy: 0.4322183639241254
Precision: 0.38078349167080106
Recall: 0.39333996762084494
F1_macro: 0.35354494877360787

--- CHOL: knn ---
Accuracy: 0.6217147379113221
Precision: 0.36433821903340347
Recall: 0.33949659244951624
F1_macro: 0.3008003970073593

--- CHOL: mlp ---
Accuracy: 0.5808966999740155
Precision: 0.3795330304372709
Recall: 0.3654220930103732
F1_macro: 0.3612881466785069

--- CHOL: gb ---
Accuracy: 0.6452867739116057
Precision: 0.2487677574670244
Recall: 0.33342236994102514
F1_macro: 0.2623143298346896

--- CHOL: hgb ---
Accuracy: 0.6455294923582077
Precision: 0.21517649745273587
Recall: 0.33333333333333337
F1_macro: 0.26152851336307964

--- CHOL: voting_clf ---
Accuracy: 0.6430958117780454
Precision: 0.35838073752949967
Recall: 0.34207485889264355
F1_macro: 0.2837956262664401

--- CHOL: voting_clf_soft ---
Accuracy: 0.6450434649091725
Precision: 0.21538246559380392
Recall: 0.33308223388660335
F1_macro: 0.26160235957696115

--- CHOL: stacking_clf ---
Accuracy: 0.4679050622445846
Precision: 0.36248560850675293
Recall: 0.3957241728252065
F1_macro: 0.3237558879988812

grid random search w f1_macro

05/09/26 running cv with new f1 params

In [ ]:
#f1 based params
models = {
    "stump": DecisionTreeClassifier(criterion= 'gini', max_depth=1, random_state=42, class_weight="balanced"),
    "tree": DecisionTreeClassifier(criterion= 'gini', max_depth=None, max_features= None, min_samples_leaf=1, min_samples_split=5, random_state=42, class_weight="balanced"),
    "rf": RandomForestClassifier(criterion='gini', max_depth= 9, max_features= 'sqrt', min_samples_leaf=4, min_samples_split=2, n_estimators=100, random_state=42, class_weight="balanced"),
    "ada": AdaBoostClassifier(n_estimators=200, learning_rate =1.0, random_state=42),
    "svm": SVC(kernel='rbf', gamma='scale', C=1, random_state=42, class_weight="balanced"),
    "nb": GaussianNB(var_smoothing= 1e-09),
    "logreg": LogisticRegression(C= 10, max_iter= 1000, penalty= 'l2', solver='sag', random_state=42, class_weight="balanced"),
    "knn": KNeighborsClassifier(algorithm= 'ball_tree', metric='manhattan', n_neighbors= 3, weights= 'uniform'),
    "mlp": MLPClassifier(solver='adam', max_iter= 500, learning_rate= 'adaptive', hidden_layer_sizes=(100,),alpha= 0.0001, activation='relu', random_state=42),
    "gb": GradientBoostingClassifier(learning_rate= 1.0, max_depth= 3, n_estimators= 200, random_state=42),
    "hgb": HistGradientBoostingClassifier(max_iter= 100, max_depth= 5, learning_rate= 1.0, l2_regularization= 0.5, random_state=42),

    "voting_clf": VotingClassifier(estimators=[
    ('stump',DecisionTreeClassifier(criterion= 'gini', max_depth=1, random_state=42, class_weight="balanced")),
    ('ada', AdaBoostClassifier(n_estimators=200, learning_rate =1.0, random_state=42)),
    ('tree', DecisionTreeClassifier(criterion= 'gini', max_depth=None, max_features= None, min_samples_leaf=1, min_samples_split=5, random_state=42, class_weight="balanced")),
    ('rfc',RandomForestClassifier(criterion='gini', max_depth= 9, max_features= 'sqrt', min_samples_leaf=4, min_samples_split=2, n_estimators=100, random_state=42, class_weight="balanced")),
    ('nb', GaussianNB(var_smoothing= 1e-09)),
    ('lr', LogisticRegression(C= 10, max_iter= 1000, penalty= 'l2', solver='sag', random_state=42, class_weight="balanced")),
    ('knn', KNeighborsClassifier(algorithm= 'ball_2tree', metric='manhattan', n_neighbors= 3, weights= 'uniform')),
    ('svm', SVC(kernel='rbf', gamma='scale', C=1, random_state=42, class_weight="balanced")),
     ('mlp', MLPClassifier(solver='adam', max_iter= 500, learning_rate= 'adaptive', hidden_layer_sizes=(100,),alpha= 0.0001, activation='relu', random_state=42)),
     ('gb', GradientBoostingClassifier(learning_rate= 1.0, max_depth= 3, n_estimators= 200, random_state=42)),
     ('hgb', HistGradientBoostingClassifier(max_iter= 100, max_depth= 5, learning_rate= 1.0, l2_regularization= 0.5, random_state=42)),
    ], voting='hard'),

    "voting_clf_soft": VotingClassifier(estimators=[
        ('ada', AdaBoostClassifier(n_estimators=50, learning_rate = 0.01, random_state=42)),
        ('rfc', RandomForestClassifier(criterion='gini', max_depth= 9, max_features= 'sqrt', min_samples_leaf=4, min_samples_split=2, n_estimators=100, random_state=42, class_weight="balanced")),
        ('nb', GaussianNB(var_smoothing= 1e-09)),
        ('lr', LogisticRegression(C= 10, max_iter= 1000, penalty= 'l2', solver='sag', random_state=42, class_weight="balanced")),
        ('svm',SVC(kernel='rbf', gamma='scale', C=1, random_state=42, probability= True, class_weight="balanced")),
        ('gb', GradientBoostingClassifier(learning_rate= 1.0, max_depth= 3, n_estimators= 200, random_state=42)),
        ('hgb', HistGradientBoostingClassifier(max_iter= 100, max_depth= 5, learning_rate= 1.0, l2_regularization= 0.5, random_state=42)),
    ], voting='soft'),

    "stacking_clf": StackingClassifier(
        estimators=[
            ('ada', AdaBoostClassifier(n_estimators=50, learning_rate = 0.01, random_state=42)),
            ('tree',  DecisionTreeClassifier(criterion= 'gini', max_depth=None, max_features= None, min_samples_leaf=1, min_samples_split=5, random_state=42, class_weight="balanced")),
            ('rfc', RandomForestClassifier(criterion='gini', max_depth= 9, max_features= 'sqrt', min_samples_leaf=4, min_samples_split=2, n_estimators=100, random_state=42, class_weight="balanced")),
            ('nb', GaussianNB(var_smoothing= 1e-09)),
            ('lr', LogisticRegression(C= 10, max_iter= 1000, penalty= 'l2', solver='sag', random_state=42, class_weight="balanced")),
            ('svm', SVC(kernel='rbf', gamma='scale', C=1, random_state=42, class_weight="balanced")),
            ('gb', GradientBoostingClassifier(learning_rate= 1.0, max_depth= 3, n_estimators= 200, random_state=42)),
            ('hgb', HistGradientBoostingClassifier(max_iter= 100, max_depth= 5, learning_rate= 1.0, l2_regularization= 0.5, random_state=42)),
        ],
        final_estimator=LogisticRegression(C= 10, max_iter= 1000, penalty= 'l2', solver='sag', random_state=42, class_weight="balanced")
    )
}

In [ ]:
chol_results = {}

for name in models:
    chol_cv = cross_validate(make_pipeline(plinec,models[name]), chol_training_purple.drop(columns=['CHOL']), chol_training_purple['CHOL'], cv=10, scoring=scoring_list)
    print(f"\n--- CHOL: {name} ---")
    chol_results[name] = chol_cv
    print(chol_results[name])
    print("Accuracy:", chol_results[name]["test_accuracy"].mean())
    print("Precision:", chol_results[name]["test_precision_macro"].mean())
    print("Recall:", chol_results[name]["test_recall_macro"].mean())
    print("F1_macro:", chol_results[name]["test_f1_macro"].mean())

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: stump ---
{'fit_time': array([0.88934827, 0.66867971, 0.27937317, 0.48501134, 0.25761318,
       0.23778892, 0.31255078, 0.29022479, 0.22480726, 0.4849689 ]), 'score_time': array([0.07881975, 0.08602428, 0.0566113 , 0.05426264, 0.05572248,
       0.05486822, 0.0615871 , 0.05513263, 0.05492878, 0.06290364]), 'test_accuracy': array([0.48786408, 0.4684466 , 0.48786408, 0.52427184, 0.51699029,
       0.45145631, 0.52554745, 0.49878345, 0.50121655, 0.45985401]), 'test_precision_macro': array([0.28314392, 0.27655502, 0.28559177, 0.29356337, 0.27431778,
       0.25916907, 0.27644757, 0.29037205, 0.28974009, 0.27518127]), 'test_recall_macro': array([0.39785634, 0.38199221, 0.41537354, 0.4224924 , 0.36618141,
       0.35260025, 0.37577988, 0.41538873, 0.41081226, 0.38942861]), 'test_f1_macro': array([0.30690728, 0.29509483, 0.31287243, 0.32833722, 0.30233766,
       0.27929057, 0.3088483 , 0.31687508, 0.31612055, 0.29453092])}
Accuracy: 0.4922294663737509
Precision: 0.2804081907378314
Recall: 0.39279056357272146
F1_macro: 0.306121482305952

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: tree ---
{'fit_time': array([0.61350894, 0.50367928, 0.39699936, 0.61598921, 0.52822566,
       0.40957642, 0.40318036, 0.53094888, 0.40101361, 0.55554605]), 'score_time': array([0.04387903, 0.04093289, 0.04315591, 0.0513041 , 0.04118562,
       0.04108167, 0.04049301, 0.04069209, 0.04106236, 0.0405848 ]), 'test_accuracy': array([0.5315534 , 0.45631068, 0.47087379, 0.47330097, 0.52912621,
       0.47330097, 0.48418491, 0.44038929, 0.49878345, 0.47688564]), 'test_precision_macro': array([0.38733333, 0.34745796, 0.32184371, 0.34873714, 0.38762549,
       0.3496284 , 0.3328421 , 0.31534895, 0.36245507, 0.34023462]), 'test_recall_macro': array([0.38718115, 0.35749943, 0.32092212, 0.35348445, 0.38804189,
       0.35219   , 0.33166884, 0.31168233, 0.36520835, 0.34172584]), 'test_f1_macro': array([0.38635735, 0.34528969, 0.32114576, 0.3494494 , 0.3871869 ,
       0.34987414, 0.33173515, 0.31153447, 0.36301659, 0.34007446])}
Accuracy: 0.48347093284199083
Precision: 0.34935067745924414
Recall: 0.35096043921273395
F1_macro: 0.34856639039278076

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: rf ---
{'fit_time': array([2.15367532, 3.2211678 , 2.30398417, 2.2029624 , 1.9143579 ,
       1.99159503, 1.86959863, 2.60138559, 2.98878288, 2.15171146]), 'score_time': array([0.08616161, 0.08649278, 0.05405331, 0.05316472, 0.05129647,
       0.05366206, 0.06399703, 0.07766271, 0.05478144, 0.05437303]), 'test_accuracy': array([0.58980583, 0.51699029, 0.56067961, 0.55097087, 0.55097087,
       0.56067961, 0.54014599, 0.52068127, 0.55231144, 0.53284672]), 'test_precision_macro': array([0.43800253, 0.37445887, 0.40426747, 0.41171238, 0.38952067,
       0.41095625, 0.3698883 , 0.35836304, 0.38020977, 0.37381536]), 'test_recall_macro': array([0.42742683, 0.37392697, 0.40332752, 0.39147083, 0.38985951,
       0.40224072, 0.36847819, 0.35853301, 0.37488521, 0.37164283]), 'test_f1_macro': array([0.43097656, 0.37375399, 0.40340622, 0.3982321 , 0.38822862,
       0.40522584, 0.36820328, 0.35804503, 0.37578768, 0.37188639])}
Accuracy: 0.5476082488838494
Precision: 0.39111946424929667
Recall: 0.38617916209958086
F1_macro: 0.3873745694663552

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: ada ---
{'fit_time': array([4.57671261, 5.19957662, 5.24656224, 4.6037569 , 5.30136037,
       6.21614647, 4.41689277, 5.98113489, 4.33971834, 4.51108718]), 'score_time': array([0.09528685, 0.15402746, 0.09818053, 0.09289026, 0.1434269 ,
       0.09132934, 0.0904038 , 0.09151554, 0.09527659, 0.09216905]), 'test_accuracy': array([0.64563107, 0.64563107, 0.64563107, 0.64563107, 0.64563107,
       0.64563107, 0.64963504, 0.64720195, 0.64476886, 0.64476886]), 'test_precision_macro': array([0.28370188, 0.21521036, 0.21521036, 0.21521036, 0.21521036,
       0.21521036, 0.5495935 , 0.54878049, 0.21492295, 0.21492295]), 'test_recall_macro': array([0.3354472 , 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33673469, 0.33670034, 0.33333333, 0.33333333]), 'test_f1_macro': array([0.26891645, 0.26155359, 0.26155359, 0.26155359, 0.26155359,
       0.26155359, 0.26906142, 0.26839506, 0.26134122, 0.26134122])}
Accuracy: 0.6460161103630737
Precision: 0.2887973551675455
Recall: 0.33422155677794774
F1_macro: 0.2636823322925438

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: svm ---
{'fit_time': array([1.91710544, 2.51601529, 1.69625449, 2.08208585, 1.31358624,
       1.30801511, 1.29150605, 1.33811426, 1.68092966, 2.88619852]), 'score_time': array([0.26552725, 0.254215  , 0.17759943, 0.17963457, 0.18332887,
       0.1809721 , 0.18465662, 0.17466497, 0.25635529, 0.2617476 ]), 'test_accuracy': array([0.48058252, 0.42961165, 0.44902913, 0.46601942, 0.47572816,
       0.49514563, 0.40632603, 0.46472019, 0.46472019, 0.41605839]), 'test_precision_macro': array([0.42285302, 0.36405898, 0.38365939, 0.40588196, 0.4180522 ,
       0.43347441, 0.34999274, 0.40991095, 0.38758921, 0.36276818]), 'test_recall_macro': array([0.46224335, 0.35851207, 0.38122035, 0.42814564, 0.43638082,
       0.45957901, 0.34747964, 0.42330788, 0.40692784, 0.36588365]), 'test_f1_macro': array([0.41629419, 0.34228806, 0.36360868, 0.39810938, 0.40116719,
       0.42007804, 0.33038175, 0.39246304, 0.38286517, 0.34388067])}
Accuracy: 0.45479413223726173
Precision: 0.3938241030150477
Recall: 0.406968023303172
F1_macro: 0.37911361645361763

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: nb ---
{'fit_time': array([0.74804616, 0.28746247, 0.21361804, 0.43634415, 0.23422456,
       0.22857165, 0.19852114, 0.32306552, 0.20979047, 0.38104987]), 'score_time': array([0.11623621, 0.05736423, 0.05518985, 0.06064725, 0.05517554,
       0.05794311, 0.05526686, 0.0538547 , 0.05469465, 0.05878425]), 'test_accuracy': array([0.62864078, 0.63106796, 0.61893204, 0.6092233 , 0.62378641,
       0.62378641, 0.62530414, 0.60827251, 0.61800487, 0.6350365 ]), 'test_precision_macro': array([0.6367847 , 0.41653508, 0.29333808, 0.28545078, 0.368301  ,
       0.37783692, 0.36702822, 0.29799302, 0.29721285, 0.42371429]), 'test_recall_macro': array([0.34308369, 0.35551241, 0.33011822, 0.32510569, 0.34480517,
       0.34772198, 0.34508003, 0.32290198, 0.33004256, 0.36106198]), 'test_f1_macro': array([0.30355651, 0.32457378, 0.28435355, 0.27924253, 0.3113431 ,
       0.31298404, 0.31221042, 0.27666599, 0.28474372, 0.33611086])}
Accuracy: 0.6222054898070063
Precision: 0.37641949373833616
Recall: 0.3405433716228027
F1_macro: 0.3025784504556678

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: logreg ---
{'fit_time': array([2.00827551, 0.47127104, 2.18147874, 2.06188631, 1.1371026 ,
       3.55931973, 0.73809576, 2.22156024, 0.76523519, 1.61946487]), 'score_time': array([0.040802  , 0.0408783 , 0.04153013, 0.04107237, 0.05818582,
       0.06004858, 0.04004002, 0.0410707 , 0.0429287 , 0.04170179]), 'test_accuracy': array([0.43446602, 0.39805825, 0.36650485, 0.4538835 , 0.4538835 ,
       0.42475728, 0.41119221, 0.42092457, 0.44038929, 0.44768856]), 'test_precision_macro': array([0.39342262, 0.36642294, 0.3373406 , 0.40831452, 0.41116194,
       0.38901264, 0.37210216, 0.37233834, 0.38158796, 0.39623905]), 'test_recall_macro': array([0.43904006, 0.36668638, 0.34556168, 0.42671395, 0.41352818,
       0.39960765, 0.3684401 , 0.39025745, 0.38914476, 0.41836483]), 'test_f1_macro': array([0.37763024, 0.32972536, 0.31287091, 0.38725787, 0.37434293,
       0.35627497, 0.3391322 , 0.34679573, 0.35843059, 0.37385643])}
Accuracy: 0.4251748045260199
Precision: 0.382794277615603
Recall: 0.39573450368699353
F1_macro: 0.3556317231481147

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: knn ---
{'fit_time': array([0.30868936, 0.23960686, 0.22619486, 0.50590253, 0.25347877,
       0.24134874, 0.19078279, 0.27917433, 0.1988287 , 0.37295485]), 'score_time': array([0.12410831, 0.11934114, 0.11993384, 0.1237011 , 0.12056828,
       0.12268424, 0.12120223, 0.12274218, 0.1190083 , 0.1236496 ]), 'test_accuracy': array([0.58495146, 0.55582524, 0.55582524, 0.55825243, 0.58009709,
       0.5461165 , 0.51581509, 0.5620438 , 0.55474453, 0.55474453]), 'test_precision_macro': array([0.43728162, 0.40746228, 0.3246563 , 0.36607617, 0.42580299,
       0.37177013, 0.32589663, 0.35410092, 0.35937953, 0.39882567]), 'test_recall_macro': array([0.40729968, 0.37535112, 0.34826966, 0.36120093, 0.3984518 ,
       0.36777211, 0.3246033 , 0.37022034, 0.35118967, 0.37551319]), 'test_f1_macro': array([0.40902911, 0.37818386, 0.33599389, 0.35395773, 0.40053229,
       0.36327467, 0.31890875, 0.35940372, 0.34398972, 0.37483538])}
Accuracy: 0.5568415893038526
Precision: 0.37712522304481216
Recall: 0.36798718085473336
F1_macro: 0.36381091093023765

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: mlp ---
{'fit_time': array([10.76925421,  9.76240563,  8.72450185, 10.43286872,  8.97975135,
        9.64874077, 10.10033751,  8.35572457, 10.06328988, 10.28434038]), 'score_time': array([0.05089426, 0.06637216, 0.04908466, 0.04847479, 0.06559467,
       0.05003452, 0.04642463, 0.04751968, 0.04751229, 0.09421396]), 'test_accuracy': array([0.56553398, 0.5631068 , 0.53398058, 0.56796117, 0.57524272,
       0.57038835, 0.54014599, 0.55717762, 0.57907543, 0.57177616]), 'test_precision_macro': array([0.38926041, 0.37183204, 0.31568627, 0.39915436, 0.40528921,
       0.39403076, 0.37039103, 0.37211986, 0.38253677, 0.40945166]), 'test_recall_macro': array([0.3735195 , 0.36692984, 0.32591957, 0.38272557, 0.3981631 ,
       0.38652435, 0.3690838 , 0.36995054, 0.36910954, 0.38705724]), 'test_f1_macro': array([0.37557505, 0.36543422, 0.31920322, 0.38590018, 0.39915093,
       0.38625171, 0.36942657, 0.36962537, 0.3671794 , 0.39130995])}
Accuracy: 0.5624388774714761
Precision: 0.3809752382800683
Recall: 0.3728983042439493
F1_macro: 0.372905660807691

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: gb ---
{'fit_time': array([28.65126848, 28.76259875, 29.16160393, 29.83813739, 28.55935216,
       28.88497782, 29.063447  , 28.78682518, 28.61615872, 28.83943462]), 'score_time': array([0.07878256, 0.06635594, 0.07034373, 0.06522322, 0.06862259,
       0.0694766 , 0.04584599, 0.04900312, 0.04677105, 0.04881883]), 'test_accuracy': array([0.58980583, 0.59466019, 0.56553398, 0.5461165 , 0.58495146,
       0.52912621, 0.57664234, 0.56934307, 0.57907543, 0.57177616]), 'test_precision_macro': array([0.39062763, 0.40680922, 0.36441857, 0.33952622, 0.38335738,
       0.33160072, 0.37566631, 0.37628751, 0.38247067, 0.38681381]), 'test_recall_macro': array([0.36752854, 0.38905964, 0.35972749, 0.33701921, 0.36552482,
       0.3317147 , 0.36546153, 0.36309191, 0.37121868, 0.37117029]), 'test_f1_macro': array([0.36443128, 0.39019021, 0.35712705, 0.33147945, 0.36191815,
       0.32750568, 0.36329435, 0.36078214, 0.36956623, 0.37126524])}
Accuracy: 0.570703115772565
Precision: 0.3737578030385789
Recall: 0.3621516795035937
F1_macro: 0.35975597942080706

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: hgb ---
{'fit_time': array([1.36916161, 1.37166333, 2.63397145, 2.43479776, 1.17339945,
       1.21467471, 1.19175816, 1.20058107, 1.20249104, 1.33568454]), 'score_time': array([0.05890989, 0.07828522, 0.08657932, 0.05606365, 0.05689979,
       0.0564394 , 0.06828809, 0.05991459, 0.05589938, 0.07331824]), 'test_accuracy': array([0.58737864, 0.58252427, 0.58009709, 0.60679612, 0.5631068 ,
       0.59466019, 0.56934307, 0.59124088, 0.59124088, 0.58150852]), 'test_precision_macro': array([0.40272487, 0.38658419, 0.36267851, 0.4508193 , 0.34063872,
       0.39902404, 0.39295371, 0.4117965 , 0.39659891, 0.42950864]), 'test_recall_macro': array([0.3800674 , 0.36427168, 0.36040213, 0.39693662, 0.34780132,
       0.37919203, 0.38015632, 0.38284923, 0.3732897 , 0.37992693]), 'test_f1_macro': array([0.38123505, 0.36107863, 0.3541324 , 0.40236213, 0.34049376,
       0.37763025, 0.381281  , 0.38433559, 0.37090291, 0.38479318])}
Accuracy: 0.5847896440129449
Precision: 0.39733273837159333
Recall: 0.3744893377089433
F1_macro: 0.3738244896358295

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: voting_clf ---
{'fit_time': array([48.1100049 , 47.20575404, 47.8350389 , 47.75360203, 45.86162686,
       48.5490725 , 46.61681581, 48.07554364, 46.57792258, 46.96649241]), 'score_time': array([0.51674771, 0.32833266, 0.31899357, 0.33825707, 0.3317821 ,
       0.4833076 , 0.31721282, 0.32483006, 0.32888079, 0.33734155]), 'test_accuracy': array([0.62378641, 0.60436893, 0.59951456, 0.60194175, 0.62378641,
       0.58980583, 0.60583942, 0.59854015, 0.6107056 , 0.61800487]), 'test_precision_macro': array([0.46565322, 0.36557535, 0.37709596, 0.3867265 , 0.43948152,
       0.38590059, 0.40532247, 0.37007168, 0.39760728, 0.41631501]), 'test_recall_macro': array([0.41799292, 0.36236411, 0.35985784, 0.35899711, 0.39252279,
       0.37506713, 0.38143611, 0.36131312, 0.3685886 , 0.37981258]), 'test_f1_macro': array([0.42245279, 0.34814262, 0.34547548, 0.34615858, 0.38612101,
       0.36281411, 0.3780487 , 0.34430556, 0.3587126 , 0.37176819])}
Accuracy: 0.6076293907826046
Precision: 0.4009749572099877
Recall: 0.37579523067827203
F1_macro: 0.36639996328462726

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: voting_clf_soft ---
{'fit_time': array([41.55309844, 40.3767581 , 42.23641348, 41.4254694 , 39.35201049,
       41.73457098, 40.40594959, 42.1327312 , 38.77566671, 41.20416713]), 'score_time': array([0.23847246, 0.22482276, 0.22412729, 0.33483624, 0.22345161,
       0.23135829, 0.23060417, 0.34088397, 0.23592544, 0.24939251]), 'test_accuracy': array([0.63106796, 0.62621359, 0.62864078, 0.62621359, 0.63592233,
       0.60194175, 0.62043796, 0.63017032, 0.6350365 , 0.63017032]), 'test_precision_macro': array([0.56091667, 0.37005099, 0.37272727, 0.41482066, 0.34131601,
       0.36009646, 0.4270882 , 0.32367719, 0.38434405, 0.46662928]), 'test_recall_macro': array([0.36396789, 0.35189737, 0.35103663, 0.34183056, 0.3431179 ,
       0.33719716, 0.36223918, 0.34055016, 0.3531185 , 0.36648973]), 'test_f1_macro': array([0.34587582, 0.32397222, 0.32008327, 0.30276644, 0.29909001,
       0.30953933, 0.34617835, 0.29663201, 0.32058414, 0.34938857])}
Accuracy: 0.6265815085158151
Precision: 0.40216667843286336
Recall: 0.3511445076208827
F1_macro: 0.3214110150823084

/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/impute/_base.py:635: UserWarning: Skipping features without any observed values: ['HIQ032I']. At least one non-missing value is needed for imputation with strategy='most_frequent'.
  warnings.warn(

--- CHOL: stacking_clf ---
{'fit_time': array([180.05456543, 173.42529631, 180.98452497, 182.41536355,
       177.47773433, 180.67190051, 179.47468352, 181.59801006,
       178.86356235, 183.22580218]), 'score_time': array([0.2455194 , 0.24381924, 0.24073744, 0.36133838, 0.33672404,
       0.23213124, 0.24225283, 0.22567415, 0.23779655, 0.27464819]), 'test_accuracy': array([0.51941748, 0.31553398, 0.17961165, 0.29854369, 0.31553398,
       0.30097087, 0.26520681, 0.48175182, 0.33576642, 0.18978102]), 'test_precision_macro': array([0.41379225, 0.3862284 , 0.34421694, 0.34410906, 0.40625109,
       0.33820763, 0.60138327, 0.37607791, 0.2608511 , 0.35430649]), 'test_recall_macro': array([0.46397856, 0.34490751, 0.36101779, 0.37168841, 0.37320143,
       0.28813104, 0.3415644 , 0.40869284, 0.30013341, 0.41486618]), 'test_f1_macro': array([0.37552472, 0.27695239, 0.19340917, 0.25753844, 0.30309493,
       0.27203904, 0.21410911, 0.31525554, 0.23682098, 0.18838263])}
Accuracy: 0.3202117733210498
Precision: 0.38254241273475
Recall: 0.366818157035194
F1_macro: 0.2633126925297771

In [ ]:
for name in models:
    print(f"\n--- BP: {name} ---")
    print("Accuracy:", bp_results[name]["test_accuracy"].mean())
    print("Precision:", bp_results[name]["test_precision_macro"].mean())
    print("Recall:", bp_results[name]["test_recall_macro"].mean())
    print("F1_macro:", bp_results[name]["test_f1_macro"].mean())

--- BP: stump ---
Accuracy: 0.6329468150896723
Precision: 0.6271251969387724
Recall: 0.6224305599360794
F1_macro: 0.621542557325528

--- BP: tree ---
Accuracy: 0.5707854050711194
Precision: 0.5622611469248622
Recall: 0.5618448495552892
F1_macro: 0.5615609210989172

--- BP: rf ---
Accuracy: 0.6519970109255824
Precision: 0.6482829281015783
Recall: 0.6290031750036797
F1_macro: 0.627199665878164

--- BP: ada ---
Accuracy: 0.6315790558647703
Precision: 0.6282856923390281
Recall: 0.6134631342122415
F1_macro: 0.6094010831049727

--- BP: svm ---
Accuracy: 0.6177391259534117
Precision: 0.6097834061961704
Recall: 0.6081415420845687
F1_macro: 0.6082856057901559

--- BP: nb ---
Accuracy: 0.6397412904555763
Precision: 0.6322040910449424
Recall: 0.6244084274269854
F1_macro: 0.6247466533640889

--- BP: logreg ---
Accuracy: 0.6388399299113585
Precision: 0.6345905536410861
Recall: 0.6356306482474401
F1_macro: 0.6342998606159957

--- BP: knn ---
Accuracy: 0.6161616161616161
Precision: 0.6065257598852783
Recall: 0.5925779011333292
F1_macro: 0.589074226624395

--- BP: mlp ---
Accuracy: 0.6186435786435787
Precision: 0.6096880706298261
Recall: 0.6059215458693413
F1_macro: 0.6059012892626189

--- BP: gb ---
Accuracy: 0.6447351061636775
Precision: 0.6608755957262712
Recall: 0.6076845181774216
F1_macro: 0.5915405603638092

--- BP: hgb ---
Accuracy: 0.6569805194805195
Precision: 0.6767290709941338
Recall: 0.6211450787442965
F1_macro: 0.6070751408549676

--- BP: voting_clf ---
Accuracy: 0.6606163677592249
Precision: 0.6589153733560951
Recall: 0.63753549906432
F1_macro: 0.6357749001365155

--- BP: voting_clf_soft ---
Accuracy: nan
Precision: nan
Recall: nan
F1_macro: nan

--- BP: stacking_clf ---
Accuracy: 0.6628829107400536
Precision: 0.6600516313313292
Recall: 0.6411329464454677
F1_macro: 0.6403571586158334

In [ ]:
for name in models:
    print(f"\n--- CHOL: {name} ---")
    print("Accuracy:", chol_results[name]["test_accuracy"].mean())
    print("Precision:", chol_results[name]["test_precision_macro"].mean())
    print("Recall:", chol_results[name]["test_recall_macro"].mean())
    print("F1_macro:", chol_results[name]["test_f1_macro"].mean())

    #05.12.26

#     --- CHOL: stump ---
# Accuracy: 0.4922294663737509
# Precision: 0.2804081907378314
# Recall: 0.39279056357272146
# F1_macro: 0.306121482305952

# --- CHOL: tree ---
# Accuracy: 0.48347093284199083
# Precision: 0.34935067745924414
# Recall: 0.35096043921273395
# F1_macro: 0.34856639039278076

# --- CHOL: rf ---
# Accuracy: 0.5476082488838494
# Precision: 0.39111946424929667
# Recall: 0.38617916209958086
# F1_macro: 0.3873745694663552

# --- CHOL: ada ---
# Accuracy: 0.6460161103630737
# Precision: 0.2887973551675455
# Recall: 0.33422155677794774
# F1_macro: 0.2636823322925438

# --- CHOL: svm ---
# Accuracy: 0.45479413223726173
# Precision: 0.3938241030150477
# Recall: 0.406968023303172
# F1_macro: 0.37911361645361763

# --- CHOL: nb ---
# Accuracy: 0.6222054898070063
# Precision: 0.37641949373833616
# Recall: 0.3405433716228027
# F1_macro: 0.3025784504556678

# --- CHOL: logreg ---
# Accuracy: 0.4251748045260199
# Precision: 0.382794277615603
# Recall: 0.39573450368699353
# F1_macro: 0.3556317231481147

# --- CHOL: knn ---
# Accuracy: 0.5568415893038526
# Precision: 0.37712522304481216
# Recall: 0.36798718085473336
# F1_macro: 0.36381091093023765

# --- CHOL: mlp ---
# Accuracy: 0.5624388774714761
# Precision: 0.3809752382800683
# Recall: 0.3728983042439493
# F1_macro: 0.372905660807691

# --- CHOL: gb ---
# Accuracy: 0.570703115772565
# Precision: 0.3737578030385789
# Recall: 0.3621516795035937
# F1_macro: 0.35975597942080706

# --- CHOL: hgb ---
# Accuracy: 0.5847896440129449
# Precision: 0.39733273837159333
# Recall: 0.3744893377089433
# F1_macro: 0.3738244896358295

# --- CHOL: voting_clf ---
# Accuracy: 0.6076293907826046
# Precision: 0.4009749572099877
# Recall: 0.37579523067827203
# F1_macro: 0.36639996328462726

# --- CHOL: voting_clf_soft ---
# Accuracy: 0.6265815085158151
# Precision: 0.40216667843286336
# Recall: 0.3511445076208827
# F1_macro: 0.3214110150823084

# --- CHOL: stacking_clf ---
# Accuracy: 0.3202117733210498
# Precision: 0.38254241273475
# Recall: 0.366818157035194
# F1_macro: 0.2633126925297771

--- CHOL: stump ---
Accuracy: 0.4922294663737509
Precision: 0.2804081907378314
Recall: 0.39279056357272146
F1_macro: 0.306121482305952

--- CHOL: tree ---
Accuracy: 0.48347093284199083
Precision: 0.34935067745924414
Recall: 0.35096043921273395
F1_macro: 0.34856639039278076

--- CHOL: rf ---
Accuracy: 0.5476082488838494
Precision: 0.39111946424929667
Recall: 0.38617916209958086
F1_macro: 0.3873745694663552

--- CHOL: ada ---
Accuracy: 0.6460161103630737
Precision: 0.2887973551675455
Recall: 0.33422155677794774
F1_macro: 0.2636823322925438

--- CHOL: svm ---
Accuracy: 0.45479413223726173
Precision: 0.3938241030150477
Recall: 0.406968023303172
F1_macro: 0.37911361645361763

--- CHOL: nb ---
Accuracy: 0.6222054898070063
Precision: 0.37641949373833616
Recall: 0.3405433716228027
F1_macro: 0.3025784504556678

--- CHOL: logreg ---
Accuracy: 0.4251748045260199
Precision: 0.382794277615603
Recall: 0.39573450368699353
F1_macro: 0.3556317231481147

--- CHOL: knn ---
Accuracy: 0.5568415893038526
Precision: 0.37712522304481216
Recall: 0.36798718085473336
F1_macro: 0.36381091093023765

--- CHOL: mlp ---
Accuracy: 0.5624388774714761
Precision: 0.3809752382800683
Recall: 0.3728983042439493
F1_macro: 0.372905660807691

--- CHOL: gb ---
Accuracy: 0.570703115772565
Precision: 0.3737578030385789
Recall: 0.3621516795035937
F1_macro: 0.35975597942080706

--- CHOL: hgb ---
Accuracy: 0.5847896440129449
Precision: 0.39733273837159333
Recall: 0.3744893377089433
F1_macro: 0.3738244896358295

--- CHOL: voting_clf ---
Accuracy: 0.6076293907826046
Precision: 0.4009749572099877
Recall: 0.37579523067827203
F1_macro: 0.36639996328462726

--- CHOL: voting_clf_soft ---
Accuracy: 0.6265815085158151
Precision: 0.40216667843286336
Recall: 0.3511445076208827
F1_macro: 0.3214110150823084

--- CHOL: stacking_clf ---
Accuracy: 0.3202117733210498
Precision: 0.38254241273475
Recall: 0.366818157035194
F1_macro: 0.2633126925297771